export const CITATIONS_GUERRIERES = [
  "Cherchez secours dans la patience et la prière. La victoire vient avec l'endurance.",
  "Aucune âme n'est chargée au-delà de sa capacité. Tu es capable.",
  "Même si je marche dans la vallée de l'ombre, je ne crains aucun mal.",
  "Le fer aiguise le fer, tout comme un homme aiguise un autre homme.",
  "Il n'y a rien que l'on ne puisse faire avec de la détermination.",
  "Tomber sept fois, se relever huit.",
  "La douleur est temporaire. L'abandon est définitif.",
  "La sueur d'aujourd'hui épargne le sang de demain.",
  "Celui qui a conquis sur lui-même est plus grand que celui qui a conquis mille hommes au combat.",
  "N'attends pas que ce soit facile. Fais en sorte d'être capable.",
  "La discipline, c'est choisir entre ce que tu veux maintenant et ce que tu veux le plus.",
  "Un guerrier ne renonce jamais à ce qu'il aime. Il trouve l'amour dans ce qu'il fait.",
  "La seule journée facile, c'était hier.",
  "Sois fort pour être utile.",
  "Le confort est l'ennemi du progrès.",
  "C'est dans l'inconfort que l'on grandit.",
  "Ne prie pas pour une vie facile. Prie pour avoir la force d'endurer la difficulté.",
  "Tout est possible à celui qui croit.",
  "La foi déplace les montagnes, mais n'oublie pas d'apporter ta pelle.",
  "Si ton esprit peut le concevoir, ton corps peut le faire.",
  "Le lâche meurt mille fois avant sa mort. Le vaillant ne goûte la mort qu'une fois.",
  "L'entraînement bat le talent quand le talent ne s'entraîne pas.",
  "Tu ne perds jamais. Soit tu gagnes, soit tu apprends.",
  "La peur est une réaction. Le courage est une décision.",
  "Maîtrise-toi, et tu maîtriseras le monde.",
  "Agis comme si c'était impossible d'échouer.",
  "La vraie force n'est pas de frapper fort, mais de se relever à chaque fois.",
  "Ton corps peut supporter presque tout. C'est ta tête qu'il faut convaincre.",
  "Ne compte pas les jours, fais que les jours comptent.",
  "L'or est testé par le feu, l'homme brave par l'adversité.",
  "Il y a une facilité après chaque difficulté.",
  "Sois comme l'eau : insaisissable mais capable de briser la roche.",
  "Le guerrier sage évite le combat. Mais s'il doit combattre, il gagne.",
  "Rien de grand ne s'est accompli sans passion.",
  "Ton seul adversaire, c'est toi-même hier.",
  "La fatigue est une émotion. Contrôle-la.",
  "Un esprit calme est l'arme la plus puissante contre tes défis.",
  "Si tu veux la paix, prépare la guerre (contre tes faiblesses).",
  "Ne baisse pas les bras. Souffre maintenant et vis le reste de ta vie comme un champion.",
  "Les obstacles ne bloquent pas le chemin. Ils sont le chemin.",
  "La volonté de gagner ne signifie rien sans la volonté de se préparer.",
  "Ce que nous faisons dans la vie résonne dans l'éternité.",
  "Reste humble dans la victoire, et fort dans la défaite.",
  "Le succès n'est pas final, l'échec n'est pas fatal : c'est le courage de continuer qui compte.",
  "Fais ce que tu dois faire jusqu'à ce que tu puisses faire ce que tu veux faire.",
  "Personne ne viendra te sauver. Lève-toi.",
  "La douleur de la discipline pèse des grammes. La douleur du regret pèse des tonnes.",
  "Sois le changement que tu veux voir.",
  "L'honneur ne se donne pas, il se gagne.",
  "Chaque respiration est une nouvelle chance de devenir meilleur.",
  "Pour se mettre en marche, il suffit d'avoir 5% de réponses à ses questions ; les 95% restants viennent le long du chemin. — Mike Horn",
  "La volonté est la seule chose qui ne dépend que de nous. — Mike Horn",
  "On a tous deux vies. La deuxième commence quand on réalise qu'on n'en a qu'une. — Mike Horn",
  "Ne rêve pas ta vie, vis tes rêves. — Mike Horn"
];
