// ============================================
// YOROI - BIBLIOTHÈQUE MASSIVE D'EXERCICES PRO
// Classé par Sport, Muscle et Équipement
// ============================================

export interface ExerciseDefinition {
  name: string;
  category: string;
  muscle?: string;
  unit: 'reps' | 'time' | 'km' | 'meters';
}
export const EXERCISE_LIBRARY: ExerciseDefinition[] = [
  // ═══════════════════════════════════════════════════════════════
  // CARDIO (CLASSÉ PAR APPAREIL)
  // ═══════════════════════════════════════════════════════════════
  { name: 'Course (Tapis Matrix)', category: 'cardio', muscle: 'TAPIS', unit: 'km' },
  { name: 'Marche Inclinée (Matrix)', category: 'cardio', muscle: 'TAPIS', unit: 'km' },
  { name: 'Sprint Intervalles (Tapis)', category: 'cardio', muscle: 'TAPIS', unit: 'time' },
  { name: 'Vélo de Biking / Spinning', category: 'cardio', muscle: 'VÉLO', unit: 'km' },
  { name: 'Vélo Statique (Technogym)', category: 'cardio', muscle: 'VÉLO', unit: 'time' },
  { name: 'Rameur Concept2', category: 'cardio', muscle: 'RAMEUR', unit: 'km' },
  { name: 'Vélo Elliptique', category: 'cardio', muscle: 'ELLIPTIQUE', unit: 'time' },
  { name: 'Vario (Technogym)', category: 'cardio', muscle: 'ELLIPTIQUE', unit: 'time' },
  { name: 'SkiErg PM5', category: 'cardio', muscle: 'SKIERG', unit: 'time' },
  { name: 'Assault Bike (AirBike)', category: 'cardio', muscle: 'ASSAULT BIKE', unit: 'time' },
  { name: 'Stairmaster / Escaliers', category: 'cardio', muscle: 'ESCALIER', unit: 'time' },
  { name: 'Corde à sauter Speed', category: 'cardio', muscle: 'CORDE', unit: 'time' },

  // ═══════════════════════════════════════════════════════════════
  // MUSCULATION - PECTORAUX
  // ═══════════════════════════════════════════════════════════════
  { name: 'Développé Couché (Barre)', category: 'musculation', muscle: 'PECTORAUX', unit: 'reps' },
  { name: 'Développé Couché (Haltères)', category: 'musculation', muscle: 'PECTORAUX', unit: 'reps' },
  { name: 'Développé Incliné (Barre)', category: 'musculation', muscle: 'PECTORAUX', unit: 'reps' },
  { name: 'Développé Incliné (Haltères)', category: 'musculation', muscle: 'PECTORAUX', unit: 'reps' },
  { name: 'Développé Décliné (Barre)', category: 'musculation', muscle: 'PECTORAUX', unit: 'reps' },
  { name: 'Développé Décliné (Haltères)', category: 'musculation', muscle: 'PECTORAUX', unit: 'reps' },
  { name: 'Écartés Couché (Haltères)', category: 'musculation', muscle: 'PECTORAUX', unit: 'reps' },
  { name: 'Écartés Incliné (Haltères)', category: 'musculation', muscle: 'PECTORAUX', unit: 'reps' },
  { name: 'Écartés à la Poulie Haute', category: 'musculation', muscle: 'PECTORAUX', unit: 'reps' },
  { name: 'Écartés à la Poulie Basse', category: 'musculation', muscle: 'PECTORAUX', unit: 'reps' },
  { name: 'Chest Press (Machine)', category: 'musculation', muscle: 'PECTORAUX', unit: 'reps' },
  { name: 'Chest Press Incliné (Machine)', category: 'musculation', muscle: 'PECTORAUX', unit: 'reps' },
  { name: 'Pec Deck (Butterfly)', category: 'musculation', muscle: 'PECTORAUX', unit: 'reps' },
  { name: 'Dips (Focus Pectoraux)', category: 'musculation', muscle: 'PECTORAUX', unit: 'reps' },
  { name: 'Pompes (Poids du corps)', category: 'musculation', muscle: 'PECTORAUX', unit: 'reps' },
  { name: 'Pompes Déclinées', category: 'musculation', muscle: 'PECTORAUX', unit: 'reps' },
  { name: 'Pompes Diamant', category: 'musculation', muscle: 'PECTORAUX', unit: 'reps' },
  { name: 'Pull Over (Haltère)', category: 'musculation', muscle: 'PECTORAUX', unit: 'reps' },
  { name: 'Landmine Press', category: 'musculation', muscle: 'PECTORAUX', unit: 'reps' },
  { name: 'Floor Press (Haltères)', category: 'musculation', muscle: 'PECTORAUX', unit: 'reps' },

  // ═══════════════════════════════════════════════════════════════
  // MUSCULATION - DOS
  // ═══════════════════════════════════════════════════════════════
  { name: 'Tractions (Pronation)', category: 'musculation', muscle: 'DOS', unit: 'reps' },
  { name: 'Tractions (Supination)', category: 'musculation', muscle: 'DOS', unit: 'reps' },
  { name: 'Tractions Neutres', category: 'musculation', muscle: 'DOS', unit: 'reps' },
  { name: 'Tractions Larges', category: 'musculation', muscle: 'DOS', unit: 'reps' },
  { name: 'Tirage Poitrine (Lat Pulldown)', category: 'musculation', muscle: 'DOS', unit: 'reps' },
  { name: 'Tirage Nuque', category: 'musculation', muscle: 'DOS', unit: 'reps' },
  { name: 'Tirage Serré (V-Bar)', category: 'musculation', muscle: 'DOS', unit: 'reps' },
  { name: 'Rowing Barre (Bent Over)', category: 'musculation', muscle: 'DOS', unit: 'reps' },
  { name: 'Rowing Haltère (One Arm)', category: 'musculation', muscle: 'DOS', unit: 'reps' },
  { name: 'Rowing T-Bar', category: 'musculation', muscle: 'DOS', unit: 'reps' },
  { name: 'Rowing Pendlay', category: 'musculation', muscle: 'DOS', unit: 'reps' },
  { name: 'Tirage Horizontal (Seated Row)', category: 'musculation', muscle: 'DOS', unit: 'reps' },
  { name: 'Tirage Horizontal Unilatéral', category: 'musculation', muscle: 'DOS', unit: 'reps' },
  { name: 'Deadlift (Soulevé de terre)', category: 'musculation', muscle: 'DOS', unit: 'reps' },
  { name: 'Deadlift Roumain', category: 'musculation', muscle: 'DOS', unit: 'reps' },
  { name: 'Deadlift Sumo', category: 'musculation', muscle: 'DOS', unit: 'reps' },
  { name: 'Pull Over Poulie Haute', category: 'musculation', muscle: 'DOS', unit: 'reps' },
  { name: 'Banc à Lombaires', category: 'musculation', muscle: 'DOS', unit: 'reps' },
  { name: 'Low Row Machine', category: 'musculation', muscle: 'DOS', unit: 'reps' },
  { name: 'Seal Row', category: 'musculation', muscle: 'DOS', unit: 'reps' },
  { name: 'Meadows Row', category: 'musculation', muscle: 'DOS', unit: 'reps' },
  { name: 'Face Pull', category: 'musculation', muscle: 'DOS', unit: 'reps' },
  { name: 'Hyperextensions', category: 'musculation', muscle: 'DOS', unit: 'reps' },
  { name: 'Good Morning', category: 'musculation', muscle: 'DOS', unit: 'reps' },

  // ═══════════════════════════════════════════════════════════════
  // MUSCULATION - ÉPAULES
  // ═══════════════════════════════════════════════════════════════
  { name: 'Développé Militaire (Barre)', category: 'musculation', muscle: 'ÉPAULES', unit: 'reps' },
  { name: 'Développé Militaire Assis', category: 'musculation', muscle: 'ÉPAULES', unit: 'reps' },
  { name: 'Développé Haltères Assis', category: 'musculation', muscle: 'ÉPAULES', unit: 'reps' },
  { name: 'Développé Haltères Debout', category: 'musculation', muscle: 'ÉPAULES', unit: 'reps' },
  { name: 'Arnold Press', category: 'musculation', muscle: 'ÉPAULES', unit: 'reps' },
  { name: 'Push Press', category: 'musculation', muscle: 'ÉPAULES', unit: 'reps' },
  { name: 'Élévations Latérales (Haltères)', category: 'musculation', muscle: 'ÉPAULES', unit: 'reps' },
  { name: 'Élévations Latérales (Poulie)', category: 'musculation', muscle: 'ÉPAULES', unit: 'reps' },
  { name: 'Élévations Latérales (Machine)', category: 'musculation', muscle: 'ÉPAULES', unit: 'reps' },
  { name: 'Élévations Frontales (Haltères)', category: 'musculation', muscle: 'ÉPAULES', unit: 'reps' },
  { name: 'Élévations Frontales (Barre)', category: 'musculation', muscle: 'ÉPAULES', unit: 'reps' },
  { name: 'Oiseau Haltères (Rear Delts)', category: 'musculation', muscle: 'ÉPAULES', unit: 'reps' },
  { name: 'Oiseau Machine (Reverse Pec Deck)', category: 'musculation', muscle: 'ÉPAULES', unit: 'reps' },
  { name: 'Oiseau Poulie Basse', category: 'musculation', muscle: 'ÉPAULES', unit: 'reps' },
  { name: 'Shoulder Press Machine', category: 'musculation', muscle: 'ÉPAULES', unit: 'reps' },
  { name: 'Facepull Poulie', category: 'musculation', muscle: 'ÉPAULES', unit: 'reps' },
  { name: 'Shrugs Haltères (Trapèzes)', category: 'musculation', muscle: 'ÉPAULES', unit: 'reps' },
  { name: 'Shrugs Barre (Trapèzes)', category: 'musculation', muscle: 'ÉPAULES', unit: 'reps' },
  { name: 'Tirage Menton (Upright Row)', category: 'musculation', muscle: 'ÉPAULES', unit: 'reps' },
  { name: 'Lu Raises', category: 'musculation', muscle: 'ÉPAULES', unit: 'reps' },
  { name: 'Y Raises', category: 'musculation', muscle: 'ÉPAULES', unit: 'reps' },
  { name: 'Cuban Press', category: 'musculation', muscle: 'ÉPAULES', unit: 'reps' },
  { name: 'Bradford Press', category: 'musculation', muscle: 'ÉPAULES', unit: 'reps' },

  // ═══════════════════════════════════════════════════════════════
  // MUSCULATION - BICEPS
  // ═══════════════════════════════════════════════════════════════
  { name: 'Curl Barre EZ', category: 'musculation', muscle: 'BICEPS', unit: 'reps' },
  { name: 'Curl Barre Droite', category: 'musculation', muscle: 'BICEPS', unit: 'reps' },
  { name: 'Curl Haltères Alterné', category: 'musculation', muscle: 'BICEPS', unit: 'reps' },
  { name: 'Curl Haltères Simultané', category: 'musculation', muscle: 'BICEPS', unit: 'reps' },
  { name: 'Curl Marteau (Hammer)', category: 'musculation', muscle: 'BICEPS', unit: 'reps' },
  { name: 'Curl Larry Scott (Pupitre)', category: 'musculation', muscle: 'BICEPS', unit: 'reps' },
  { name: 'Curl Incliné (Haltères)', category: 'musculation', muscle: 'BICEPS', unit: 'reps' },
  { name: 'Curl Concentré', category: 'musculation', muscle: 'BICEPS', unit: 'reps' },
  { name: 'Curl Poulie Basse', category: 'musculation', muscle: 'BICEPS', unit: 'reps' },
  { name: 'Curl Poulie Haute (Spider)', category: 'musculation', muscle: 'BICEPS', unit: 'reps' },
  { name: 'Curl Machine', category: 'musculation', muscle: 'BICEPS', unit: 'reps' },
  { name: 'Curl 21s', category: 'musculation', muscle: 'BICEPS', unit: 'reps' },
  { name: 'Drag Curl', category: 'musculation', muscle: 'BICEPS', unit: 'reps' },
  { name: 'Reverse Curl (Avant-bras)', category: 'musculation', muscle: 'BICEPS', unit: 'reps' },
  { name: 'Curl Zottman', category: 'musculation', muscle: 'BICEPS', unit: 'reps' },

  // ═══════════════════════════════════════════════════════════════
  // MUSCULATION - TRICEPS
  // ═══════════════════════════════════════════════════════════════
  { name: 'Extension Triceps Poulie (Corde)', category: 'musculation', muscle: 'TRICEPS', unit: 'reps' },
  { name: 'Extension Triceps Poulie (Barre)', category: 'musculation', muscle: 'TRICEPS', unit: 'reps' },
  { name: 'Extension Triceps Poulie (V-Bar)', category: 'musculation', muscle: 'TRICEPS', unit: 'reps' },
  { name: 'Barre au front (Skullcrusher)', category: 'musculation', muscle: 'TRICEPS', unit: 'reps' },
  { name: 'Skullcrusher Haltères', category: 'musculation', muscle: 'TRICEPS', unit: 'reps' },
  { name: 'Dips (Focus Triceps)', category: 'musculation', muscle: 'TRICEPS', unit: 'reps' },
  { name: 'Dips Banc', category: 'musculation', muscle: 'TRICEPS', unit: 'reps' },
  { name: 'Extension Haltère Nuque', category: 'musculation', muscle: 'TRICEPS', unit: 'reps' },
  { name: 'Extension Haltère Nuque (2 mains)', category: 'musculation', muscle: 'TRICEPS', unit: 'reps' },
  { name: 'Kickback Triceps (Haltère)', category: 'musculation', muscle: 'TRICEPS', unit: 'reps' },
  { name: 'Kickback Triceps (Poulie)', category: 'musculation', muscle: 'TRICEPS', unit: 'reps' },
  { name: 'Close Grip Bench Press', category: 'musculation', muscle: 'TRICEPS', unit: 'reps' },
  { name: 'JM Press', category: 'musculation', muscle: 'TRICEPS', unit: 'reps' },
  { name: 'Triceps Machine', category: 'musculation', muscle: 'TRICEPS', unit: 'reps' },
  { name: 'Diamond Push-ups', category: 'musculation', muscle: 'TRICEPS', unit: 'reps' },
  { name: 'Overhead Extension Poulie', category: 'musculation', muscle: 'TRICEPS', unit: 'reps' },

  // ═══════════════════════════════════════════════════════════════
  // MUSCULATION - AVANT-BRAS
  // ═══════════════════════════════════════════════════════════════
  { name: 'Curl Poignets (Flexion)', category: 'musculation', muscle: 'AVANT-BRAS', unit: 'reps' },
  { name: 'Extension Poignets', category: 'musculation', muscle: 'AVANT-BRAS', unit: 'reps' },
  { name: 'Farmer Walk', category: 'musculation', muscle: 'AVANT-BRAS', unit: 'time' },
  { name: 'Dead Hang', category: 'musculation', muscle: 'AVANT-BRAS', unit: 'time' },
  { name: 'Gripper / Hand Grip', category: 'musculation', muscle: 'AVANT-BRAS', unit: 'reps' },
  { name: 'Plate Pinch', category: 'musculation', muscle: 'AVANT-BRAS', unit: 'time' },
  { name: 'Wrist Roller', category: 'musculation', muscle: 'AVANT-BRAS', unit: 'reps' },

  // ═══════════════════════════════════════════════════════════════
  // MUSCULATION - JAMBES (QUADRICEPS)
  // ═══════════════════════════════════════════════════════════════
  { name: 'Squat Barre Libre', category: 'musculation', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Squat Barre Haute', category: 'musculation', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Squat Barre Basse', category: 'musculation', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Front Squat', category: 'musculation', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Goblet Squat', category: 'musculation', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Squat Bulgare', category: 'musculation', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Squat Sissy', category: 'musculation', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Squat Zercher', category: 'musculation', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Presse à Cuisses', category: 'musculation', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Presse à Cuisses (Pieds Bas)', category: 'musculation', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Presse à Cuisses (Pieds Hauts)', category: 'musculation', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Presse Unilatérale', category: 'musculation', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Leg Extension', category: 'musculation', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Hack Squat', category: 'musculation', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Hack Squat Inversé', category: 'musculation', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Pendulum Squat', category: 'musculation', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Smith Machine Squat', category: 'musculation', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Fentes Avant (Haltères)', category: 'musculation', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Fentes Arrière', category: 'musculation', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Fentes Marchées', category: 'musculation', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Step Up (Haltères)', category: 'musculation', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Box Squat', category: 'musculation', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Wall Sit', category: 'musculation', muscle: 'JAMBES', unit: 'time' },

  // ═══════════════════════════════════════════════════════════════
  // MUSCULATION - ISCHIO-JAMBIERS
  // ═══════════════════════════════════════════════════════════════
  { name: 'Leg Curl Couché', category: 'musculation', muscle: 'ISCHIOS', unit: 'reps' },
  { name: 'Leg Curl Assis', category: 'musculation', muscle: 'ISCHIOS', unit: 'reps' },
  { name: 'Leg Curl Debout', category: 'musculation', muscle: 'ISCHIOS', unit: 'reps' },
  { name: 'SDT Jambes Tendues', category: 'musculation', muscle: 'ISCHIOS', unit: 'reps' },
  { name: 'Romanian Deadlift (Haltères)', category: 'musculation', muscle: 'ISCHIOS', unit: 'reps' },
  { name: 'Single Leg Deadlift', category: 'musculation', muscle: 'ISCHIOS', unit: 'reps' },
  { name: 'Nordic Curl', category: 'musculation', muscle: 'ISCHIOS', unit: 'reps' },
  { name: 'Glute Ham Raise', category: 'musculation', muscle: 'ISCHIOS', unit: 'reps' },
  { name: 'Swiss Ball Leg Curl', category: 'musculation', muscle: 'ISCHIOS', unit: 'reps' },
  { name: 'Slider Leg Curl', category: 'musculation', muscle: 'ISCHIOS', unit: 'reps' },

  // ═══════════════════════════════════════════════════════════════
  // MUSCULATION - FESSIERS
  // ═══════════════════════════════════════════════════════════════
  { name: 'Hip Thrust Barre', category: 'musculation', muscle: 'FESSIERS', unit: 'reps' },
  { name: 'Hip Thrust Machine', category: 'musculation', muscle: 'FESSIERS', unit: 'reps' },
  { name: 'Hip Thrust (Poids Corps)', category: 'musculation', muscle: 'FESSIERS', unit: 'reps' },
  { name: 'Single Leg Hip Thrust', category: 'musculation', muscle: 'FESSIERS', unit: 'reps' },
  { name: 'Glute Bridge', category: 'musculation', muscle: 'FESSIERS', unit: 'reps' },
  { name: 'Fentes Bulgares', category: 'musculation', muscle: 'FESSIERS', unit: 'reps' },
  { name: 'Abducteurs Machine', category: 'musculation', muscle: 'FESSIERS', unit: 'reps' },
  { name: 'Adducteurs Machine', category: 'musculation', muscle: 'FESSIERS', unit: 'reps' },
  { name: 'Kick-back Poulie', category: 'musculation', muscle: 'FESSIERS', unit: 'reps' },
  { name: 'Kick-back Machine', category: 'musculation', muscle: 'FESSIERS', unit: 'reps' },
  { name: 'Donkey Kicks', category: 'musculation', muscle: 'FESSIERS', unit: 'reps' },
  { name: 'Fire Hydrants', category: 'musculation', muscle: 'FESSIERS', unit: 'reps' },
  { name: 'Clamshells', category: 'musculation', muscle: 'FESSIERS', unit: 'reps' },
  { name: 'Sumo Deadlift', category: 'musculation', muscle: 'FESSIERS', unit: 'reps' },
  { name: 'Cable Pull Through', category: 'musculation', muscle: 'FESSIERS', unit: 'reps' },
  { name: 'Banded Walks', category: 'musculation', muscle: 'FESSIERS', unit: 'reps' },
  { name: 'Reverse Lunges', category: 'musculation', muscle: 'FESSIERS', unit: 'reps' },
  { name: 'Curtsy Lunges', category: 'musculation', muscle: 'FESSIERS', unit: 'reps' },

  // ═══════════════════════════════════════════════════════════════
  // MUSCULATION - MOLLETS
  // ═══════════════════════════════════════════════════════════════
  { name: 'Mollets Debout (Machine)', category: 'musculation', muscle: 'MOLLETS', unit: 'reps' },
  { name: 'Mollets Assis (Machine)', category: 'musculation', muscle: 'MOLLETS', unit: 'reps' },
  { name: 'Mollets à la Presse', category: 'musculation', muscle: 'MOLLETS', unit: 'reps' },
  { name: 'Mollets Haltères (Debout)', category: 'musculation', muscle: 'MOLLETS', unit: 'reps' },
  { name: 'Mollets Unilatéral', category: 'musculation', muscle: 'MOLLETS', unit: 'reps' },
  { name: 'Donkey Calf Raise', category: 'musculation', muscle: 'MOLLETS', unit: 'reps' },
  { name: 'Tibialis Raise', category: 'musculation', muscle: 'MOLLETS', unit: 'reps' },

  // ═══════════════════════════════════════════════════════════════
  // MUSCULATION - ABDOMINAUX
  // ═══════════════════════════════════════════════════════════════
  { name: 'Crunch Abdominal', category: 'musculation', muscle: 'ABDOS', unit: 'reps' },
  { name: 'Crunch Inversé', category: 'musculation', muscle: 'ABDOS', unit: 'reps' },
  { name: 'Crunch Poulie Haute', category: 'musculation', muscle: 'ABDOS', unit: 'reps' },
  { name: 'Crunch Machine', category: 'musculation', muscle: 'ABDOS', unit: 'reps' },
  { name: 'Relevé de jambes Suspendu', category: 'musculation', muscle: 'ABDOS', unit: 'reps' },
  { name: 'Relevé de jambes (Banc)', category: 'musculation', muscle: 'ABDOS', unit: 'reps' },
  { name: 'Relevé de jambes (Sol)', category: 'musculation', muscle: 'ABDOS', unit: 'reps' },
  { name: 'Gainage Planche', category: 'musculation', muscle: 'ABDOS', unit: 'time' },
  { name: 'Gainage Latéral', category: 'musculation', muscle: 'ABDOS', unit: 'time' },
  { name: 'Gainage Dynamique', category: 'musculation', muscle: 'ABDOS', unit: 'time' },
  { name: 'Russian Twist', category: 'musculation', muscle: 'ABDOS', unit: 'reps' },
  { name: 'Russian Twist (Lesté)', category: 'musculation', muscle: 'ABDOS', unit: 'reps' },
  { name: 'Roulette Abdos (Abs Wheel)', category: 'musculation', muscle: 'ABDOS', unit: 'reps' },
  { name: 'Sit-ups', category: 'musculation', muscle: 'ABDOS', unit: 'reps' },
  { name: 'V-ups', category: 'musculation', muscle: 'ABDOS', unit: 'reps' },
  { name: 'Bicycle Crunches', category: 'musculation', muscle: 'ABDOS', unit: 'reps' },
  { name: 'Mountain Climbers', category: 'musculation', muscle: 'ABDOS', unit: 'reps' },
  { name: 'Dead Bug', category: 'musculation', muscle: 'ABDOS', unit: 'reps' },
  { name: 'Bird Dog', category: 'musculation', muscle: 'ABDOS', unit: 'reps' },
  { name: 'Hollow Hold', category: 'musculation', muscle: 'ABDOS', unit: 'time' },
  { name: 'L-Sit', category: 'musculation', muscle: 'ABDOS', unit: 'time' },
  { name: 'Toes to Bar', category: 'musculation', muscle: 'ABDOS', unit: 'reps' },
  { name: 'Windshield Wipers', category: 'musculation', muscle: 'ABDOS', unit: 'reps' },
  { name: 'Dragon Flag', category: 'musculation', muscle: 'ABDOS', unit: 'reps' },
  { name: 'Pallof Press', category: 'musculation', muscle: 'ABDOS', unit: 'reps' },
  { name: 'Woodchop Poulie', category: 'musculation', muscle: 'ABDOS', unit: 'reps' },

  // ═══════════════════════════════════════════════════════════════
  // STREET WORKOUT / CALISTHENICS
  // ═══════════════════════════════════════════════════════════════
  { name: 'Planche (Hold)', category: 'street_workout', muscle: 'STATIQUE', unit: 'time' },
  { name: 'Straddle Planche', category: 'street_workout', muscle: 'STATIQUE', unit: 'time' },
  { name: 'Tuck Planche', category: 'street_workout', muscle: 'STATIQUE', unit: 'time' },
  { name: 'Front Lever (Hold)', category: 'street_workout', muscle: 'STATIQUE', unit: 'time' },
  { name: 'Tuck Front Lever', category: 'street_workout', muscle: 'STATIQUE', unit: 'time' },
  { name: 'Back Lever (Hold)', category: 'street_workout', muscle: 'STATIQUE', unit: 'time' },
  { name: 'Human Flag (Drapeau)', category: 'street_workout', muscle: 'STATIQUE', unit: 'time' },
  { name: 'L-Sit', category: 'street_workout', muscle: 'STATIQUE', unit: 'time' },
  { name: 'V-Sit', category: 'street_workout', muscle: 'STATIQUE', unit: 'time' },
  { name: 'Manna', category: 'street_workout', muscle: 'STATIQUE', unit: 'time' },
  { name: 'Handstand (ATR)', category: 'street_workout', muscle: 'STATIQUE', unit: 'time' },
  { name: 'Muscle Up', category: 'street_workout', muscle: 'DYNAMIQUE', unit: 'reps' },
  { name: 'Bar Muscle Up', category: 'street_workout', muscle: 'DYNAMIQUE', unit: 'reps' },
  { name: 'Ring Muscle Up', category: 'street_workout', muscle: 'DYNAMIQUE', unit: 'reps' },
  { name: 'Tractions Lestées', category: 'street_workout', muscle: 'DYNAMIQUE', unit: 'reps' },
  { name: 'Dips Lestés', category: 'street_workout', muscle: 'DYNAMIQUE', unit: 'reps' },
  { name: 'Handstand Push-ups', category: 'street_workout', muscle: 'DYNAMIQUE', unit: 'reps' },
  { name: 'HSPU Wall', category: 'street_workout', muscle: 'DYNAMIQUE', unit: 'reps' },
  { name: 'One Arm Pull-up', category: 'street_workout', muscle: 'DYNAMIQUE', unit: 'reps' },
  { name: 'One Arm Push-up', category: 'street_workout', muscle: 'DYNAMIQUE', unit: 'reps' },
  { name: 'Pistol Squat', category: 'street_workout', muscle: 'DYNAMIQUE', unit: 'reps' },
  { name: 'Shrimp Squat', category: 'street_workout', muscle: 'DYNAMIQUE', unit: 'reps' },
  { name: 'Skin the Cat', category: 'street_workout', muscle: 'DYNAMIQUE', unit: 'reps' },
  { name: '360 Pull', category: 'street_workout', muscle: 'DYNAMIQUE', unit: 'reps' },
  { name: 'Hefesto', category: 'street_workout', muscle: 'DYNAMIQUE', unit: 'reps' },
  { name: 'Impossible Dips', category: 'street_workout', muscle: 'DYNAMIQUE', unit: 'reps' },

  // ═══════════════════════════════════════════════════════════════
  // HYROX
  // ═══════════════════════════════════════════════════════════════
  { name: '1000m SkiErg', category: 'hyrox', muscle: 'STATIONS', unit: 'time' },
  { name: '50m Sled Push', category: 'hyrox', muscle: 'STATIONS', unit: 'time' },
  { name: '50m Sled Pull', category: 'hyrox', muscle: 'STATIONS', unit: 'time' },
  { name: '80m Burpee Broad Jumps', category: 'hyrox', muscle: 'STATIONS', unit: 'time' },
  { name: '1000m Rameur', category: 'hyrox', muscle: 'STATIONS', unit: 'time' },
  { name: '200m Farmers Carry', category: 'hyrox', muscle: 'STATIONS', unit: 'time' },
  { name: '100m Sandbag Lunges', category: 'hyrox', muscle: 'STATIONS', unit: 'time' },
  { name: '100 Wall Balls', category: 'hyrox', muscle: 'STATIONS', unit: 'time' },
  { name: '1km Run (Hyrox)', category: 'hyrox', muscle: 'COURSE', unit: 'time' },

  // ═══════════════════════════════════════════════════════════════
  // JJB (JIU-JITSU BRÉSILIEN) - MASSIF
  // ═══════════════════════════════════════════════════════════════
  // GARDES
  { name: 'Garde Fermée', category: 'jjb', muscle: 'GARDES', unit: 'time' },
  { name: 'Demi-Garde', category: 'jjb', muscle: 'GARDES', unit: 'time' },
  { name: 'Garde Papillon', category: 'jjb', muscle: 'GARDES', unit: 'time' },
  { name: 'De La Riva', category: 'jjb', muscle: 'GARDES', unit: 'time' },
  { name: 'Reverse De La Riva', category: 'jjb', muscle: 'GARDES', unit: 'time' },
  { name: 'Spider Guard', category: 'jjb', muscle: 'GARDES', unit: 'time' },
  { name: 'Lasso Guard', category: 'jjb', muscle: 'GARDES', unit: 'time' },
  { name: 'X-Guard', category: 'jjb', muscle: 'GARDES', unit: 'time' },
  { name: 'Single Leg X', category: 'jjb', muscle: 'GARDES', unit: 'time' },
  { name: 'Collar Sleeve Guard', category: 'jjb', muscle: 'GARDES', unit: 'time' },
  { name: 'Seated Guard', category: 'jjb', muscle: 'GARDES', unit: 'time' },
  { name: 'Rubber Guard', category: 'jjb', muscle: 'GARDES', unit: 'time' },
  { name: 'Worm Guard', category: 'jjb', muscle: 'GARDES', unit: 'time' },
  { name: 'Squid Guard', category: 'jjb', muscle: 'GARDES', unit: 'time' },
  { name: 'Z-Guard (Knee Shield)', category: 'jjb', muscle: 'GARDES', unit: 'time' },
  { name: '50/50 Guard', category: 'jjb', muscle: 'GARDES', unit: 'time' },
  { name: 'K-Guard', category: 'jjb', muscle: 'GARDES', unit: 'time' },
  { name: 'Shin to Shin', category: 'jjb', muscle: 'GARDES', unit: 'time' },
  { name: 'Williams Guard', category: 'jjb', muscle: 'GARDES', unit: 'time' },
  { name: 'Octopus Guard', category: 'jjb', muscle: 'GARDES', unit: 'time' },

  // PASSAGES DE GARDE
  { name: 'Knee Cut Pass', category: 'jjb', muscle: 'PASSAGES', unit: 'reps' },
  { name: 'Torreando Pass', category: 'jjb', muscle: 'PASSAGES', unit: 'reps' },
  { name: 'Stack Pass', category: 'jjb', muscle: 'PASSAGES', unit: 'reps' },
  { name: 'Leg Drag', category: 'jjb', muscle: 'PASSAGES', unit: 'reps' },
  { name: 'Smash Pass', category: 'jjb', muscle: 'PASSAGES', unit: 'reps' },
  { name: 'Body Lock Pass', category: 'jjb', muscle: 'PASSAGES', unit: 'reps' },
  { name: 'X-Pass', category: 'jjb', muscle: 'PASSAGES', unit: 'reps' },
  { name: 'Leg Weave', category: 'jjb', muscle: 'PASSAGES', unit: 'reps' },
  { name: 'Long Step Pass', category: 'jjb', muscle: 'PASSAGES', unit: 'reps' },
  { name: 'Over Under Pass', category: 'jjb', muscle: 'PASSAGES', unit: 'reps' },
  { name: 'Double Under Pass', category: 'jjb', muscle: 'PASSAGES', unit: 'reps' },
  { name: 'Standing Pass', category: 'jjb', muscle: 'PASSAGES', unit: 'reps' },
  { name: 'Headquarters Pass', category: 'jjb', muscle: 'PASSAGES', unit: 'reps' },
  { name: 'Backstep Pass', category: 'jjb', muscle: 'PASSAGES', unit: 'reps' },
  { name: 'Cartwheel Pass', category: 'jjb', muscle: 'PASSAGES', unit: 'reps' },

  // SWEEPS
  { name: 'Scissor Sweep', category: 'jjb', muscle: 'SWEEPS', unit: 'reps' },
  { name: 'Hip Bump Sweep', category: 'jjb', muscle: 'SWEEPS', unit: 'reps' },
  { name: 'Flower Sweep', category: 'jjb', muscle: 'SWEEPS', unit: 'reps' },
  { name: 'Pendulum Sweep', category: 'jjb', muscle: 'SWEEPS', unit: 'reps' },
  { name: 'Butterfly Sweep', category: 'jjb', muscle: 'SWEEPS', unit: 'reps' },
  { name: 'Elevator Sweep', category: 'jjb', muscle: 'SWEEPS', unit: 'reps' },
  { name: 'X-Guard Sweep', category: 'jjb', muscle: 'SWEEPS', unit: 'reps' },
  { name: 'Waiter Sweep', category: 'jjb', muscle: 'SWEEPS', unit: 'reps' },
  { name: 'Sickle Sweep', category: 'jjb', muscle: 'SWEEPS', unit: 'reps' },
  { name: 'Tripod Sweep', category: 'jjb', muscle: 'SWEEPS', unit: 'reps' },
  { name: 'Overhead Sweep', category: 'jjb', muscle: 'SWEEPS', unit: 'reps' },
  { name: 'Spider Sweep', category: 'jjb', muscle: 'SWEEPS', unit: 'reps' },
  { name: 'Lasso Sweep', category: 'jjb', muscle: 'SWEEPS', unit: 'reps' },
  { name: 'DLR Sweep', category: 'jjb', muscle: 'SWEEPS', unit: 'reps' },
  { name: 'Berimbolo', category: 'jjb', muscle: 'SWEEPS', unit: 'reps' },
  { name: 'Kiss of the Dragon', category: 'jjb', muscle: 'SWEEPS', unit: 'reps' },

  // SOUMISSIONS - ÉTRANGLEMENTS
  { name: 'Rear Naked Choke (RNC)', category: 'jjb', muscle: 'SOUMISSIONS', unit: 'reps' },
  { name: 'Triangle (Choke)', category: 'jjb', muscle: 'SOUMISSIONS', unit: 'reps' },
  { name: 'Arm Triangle', category: 'jjb', muscle: 'SOUMISSIONS', unit: 'reps' },
  { name: 'D\'arce Choke', category: 'jjb', muscle: 'SOUMISSIONS', unit: 'reps' },
  { name: 'Anaconda Choke', category: 'jjb', muscle: 'SOUMISSIONS', unit: 'reps' },
  { name: 'Guillotine', category: 'jjb', muscle: 'SOUMISSIONS', unit: 'reps' },
  { name: 'Guillotine High Elbow', category: 'jjb', muscle: 'SOUMISSIONS', unit: 'reps' },
  { name: 'Von Flue Choke', category: 'jjb', muscle: 'SOUMISSIONS', unit: 'reps' },
  { name: 'North South Choke', category: 'jjb', muscle: 'SOUMISSIONS', unit: 'reps' },
  { name: 'Ezekiel Choke', category: 'jjb', muscle: 'SOUMISSIONS', unit: 'reps' },
  { name: 'Bow and Arrow', category: 'jjb', muscle: 'SOUMISSIONS', unit: 'reps' },
  { name: 'Cross Collar Choke', category: 'jjb', muscle: 'SOUMISSIONS', unit: 'reps' },
  { name: 'Baseball Bat Choke', category: 'jjb', muscle: 'SOUMISSIONS', unit: 'reps' },
  { name: 'Brabo Choke', category: 'jjb', muscle: 'SOUMISSIONS', unit: 'reps' },
  { name: 'Paper Cutter Choke', category: 'jjb', muscle: 'SOUMISSIONS', unit: 'reps' },
  { name: 'Clock Choke', category: 'jjb', muscle: 'SOUMISSIONS', unit: 'reps' },
  { name: 'Loop Choke', category: 'jjb', muscle: 'SOUMISSIONS', unit: 'reps' },
  { name: 'Peruvian Necktie', category: 'jjb', muscle: 'SOUMISSIONS', unit: 'reps' },
  { name: 'Japanese Necktie', category: 'jjb', muscle: 'SOUMISSIONS', unit: 'reps' },
  { name: 'Gogoplata', category: 'jjb', muscle: 'SOUMISSIONS', unit: 'reps' },
  { name: 'Crucifix Choke', category: 'jjb', muscle: 'SOUMISSIONS', unit: 'reps' },
  { name: 'Twister', category: 'jjb', muscle: 'SOUMISSIONS', unit: 'reps' },

  // SOUMISSIONS - CLÉS DE BRAS
  { name: 'Armbar (Juji-gatame)', category: 'jjb', muscle: 'CLÉS', unit: 'reps' },
  { name: 'Kimura', category: 'jjb', muscle: 'CLÉS', unit: 'reps' },
  { name: 'Americana', category: 'jjb', muscle: 'CLÉS', unit: 'reps' },
  { name: 'Omoplata', category: 'jjb', muscle: 'CLÉS', unit: 'reps' },
  { name: 'Wristlock', category: 'jjb', muscle: 'CLÉS', unit: 'reps' },
  { name: 'Straight Armlock', category: 'jjb', muscle: 'CLÉS', unit: 'reps' },
  { name: 'Baratoplata', category: 'jjb', muscle: 'CLÉS', unit: 'reps' },
  { name: 'Monoplata', category: 'jjb', muscle: 'CLÉS', unit: 'reps' },
  { name: 'Tarikoplata', category: 'jjb', muscle: 'CLÉS', unit: 'reps' },

  // SOUMISSIONS - CLÉS DE JAMBES
  { name: 'Heel Hook (Inside)', category: 'jjb', muscle: 'LEG LOCKS', unit: 'reps' },
  { name: 'Heel Hook (Outside)', category: 'jjb', muscle: 'LEG LOCKS', unit: 'reps' },
  { name: 'Straight Ankle Lock', category: 'jjb', muscle: 'LEG LOCKS', unit: 'reps' },
  { name: 'Kneebar', category: 'jjb', muscle: 'LEG LOCKS', unit: 'reps' },
  { name: 'Toe Hold', category: 'jjb', muscle: 'LEG LOCKS', unit: 'reps' },
  { name: 'Calf Slicer', category: 'jjb', muscle: 'LEG LOCKS', unit: 'reps' },
  { name: 'Estima Lock', category: 'jjb', muscle: 'LEG LOCKS', unit: 'reps' },
  { name: 'Texas Cloverleaf', category: 'jjb', muscle: 'LEG LOCKS', unit: 'reps' },
  { name: 'Banana Split', category: 'jjb', muscle: 'LEG LOCKS', unit: 'reps' },
  { name: 'Aoki Lock', category: 'jjb', muscle: 'LEG LOCKS', unit: 'reps' },

  // POSITIONS DOMINANTES
  { name: 'Mount Control', category: 'jjb', muscle: 'CONTRÔLE', unit: 'time' },
  { name: 'Back Control', category: 'jjb', muscle: 'CONTRÔLE', unit: 'time' },
  { name: 'Side Control', category: 'jjb', muscle: 'CONTRÔLE', unit: 'time' },
  { name: 'Knee on Belly', category: 'jjb', muscle: 'CONTRÔLE', unit: 'time' },
  { name: 'North South', category: 'jjb', muscle: 'CONTRÔLE', unit: 'time' },
  { name: 'Crucifix Position', category: 'jjb', muscle: 'CONTRÔLE', unit: 'time' },
  { name: 'Truck Position', category: 'jjb', muscle: 'CONTRÔLE', unit: 'time' },
  { name: 'Body Triangle', category: 'jjb', muscle: 'CONTRÔLE', unit: 'time' },
  { name: 'Gift Wrap', category: 'jjb', muscle: 'CONTRÔLE', unit: 'time' },

  // ESCAPES
  { name: 'Bridge & Roll (Mount Escape)', category: 'jjb', muscle: 'ESCAPES', unit: 'reps' },
  { name: 'Elbow Escape (Mount)', category: 'jjb', muscle: 'ESCAPES', unit: 'reps' },
  { name: 'Hip Escape (Shrimp)', category: 'jjb', muscle: 'ESCAPES', unit: 'reps' },
  { name: 'Side Control Escape', category: 'jjb', muscle: 'ESCAPES', unit: 'reps' },
  { name: 'Back Escape', category: 'jjb', muscle: 'ESCAPES', unit: 'reps' },
  { name: 'Knee on Belly Escape', category: 'jjb', muscle: 'ESCAPES', unit: 'reps' },
  { name: 'Turtle Escape', category: 'jjb', muscle: 'ESCAPES', unit: 'reps' },
  { name: 'Guard Recovery', category: 'jjb', muscle: 'ESCAPES', unit: 'reps' },

  // TAKEDOWNS JJB
  { name: 'Single Leg Takedown', category: 'jjb', muscle: 'LUTTE', unit: 'reps' },
  { name: 'Double Leg Takedown', category: 'jjb', muscle: 'LUTTE', unit: 'reps' },
  { name: 'Arm Drag to Back', category: 'jjb', muscle: 'LUTTE', unit: 'reps' },
  { name: 'Snapdown', category: 'jjb', muscle: 'LUTTE', unit: 'reps' },
  { name: 'Collar Drag', category: 'jjb', muscle: 'LUTTE', unit: 'reps' },
  { name: 'Ankle Pick', category: 'jjb', muscle: 'LUTTE', unit: 'reps' },
  { name: 'Guard Pull', category: 'jjb', muscle: 'LUTTE', unit: 'reps' },
  { name: 'Tomoe Nage', category: 'jjb', muscle: 'LUTTE', unit: 'reps' },
  { name: 'Uchi Mata', category: 'jjb', muscle: 'LUTTE', unit: 'reps' },

  // DRILLS & ENTRAINEMENT
  { name: 'Drilling Passage de Garde', category: 'jjb', muscle: 'DRILL', unit: 'reps' },
  { name: 'Flow Rolling', category: 'jjb', muscle: 'COMBAT', unit: 'time' },
  { name: 'Positional Sparring', category: 'jjb', muscle: 'COMBAT', unit: 'time' },
  { name: 'Rolling (Sparring)', category: 'jjb', muscle: 'COMBAT', unit: 'time' },
  { name: 'Competition Rounds', category: 'jjb', muscle: 'COMBAT', unit: 'time' },
  { name: 'Shark Tank', category: 'jjb', muscle: 'COMBAT', unit: 'time' },

  // ═══════════════════════════════════════════════════════════════
  // BOXE ANGLAISE - COMPLET
  // ═══════════════════════════════════════════════════════════════
  { name: 'Shadow Boxing', category: 'boxe', muscle: 'TECHNIQUE', unit: 'time' },
  { name: 'Shadow Boxing (Miroir)', category: 'boxe', muscle: 'TECHNIQUE', unit: 'time' },
  { name: 'Travail au Sac (Heavy Bag)', category: 'boxe', muscle: 'PUISSANCE', unit: 'time' },
  { name: 'Sac de Frappe Lourd', category: 'boxe', muscle: 'PUISSANCE', unit: 'time' },
  { name: 'Sac de Frappe Léger', category: 'boxe', muscle: 'VITESSE', unit: 'time' },
  { name: 'Double End Bag', category: 'boxe', muscle: 'PRÉCISION', unit: 'time' },
  { name: 'Speed Bag (Poire de Vitesse)', category: 'boxe', muscle: 'VITESSE', unit: 'time' },
  { name: 'Maize Bag', category: 'boxe', muscle: 'ESQUIVE', unit: 'time' },
  { name: 'Mitts / Pattes d\'ours', category: 'boxe', muscle: 'PRÉCISION', unit: 'time' },
  { name: 'Focus Mitts Défense', category: 'boxe', muscle: 'DÉFENSE', unit: 'time' },
  { name: 'Sparring Boxe', category: 'boxe', muscle: 'COMBAT', unit: 'time' },
  { name: 'Sparring Light', category: 'boxe', muscle: 'COMBAT', unit: 'time' },
  { name: 'Sparring Conditionné', category: 'boxe', muscle: 'COMBAT', unit: 'time' },
  { name: 'Corde à sauter (Rounds)', category: 'boxe', muscle: 'CARDIO', unit: 'time' },
  { name: 'Footwork Drills', category: 'boxe', muscle: 'DÉPLACEMENT', unit: 'time' },
  { name: 'Esquive (Slip Line)', category: 'boxe', muscle: 'DÉFENSE', unit: 'time' },
  { name: 'Travail au Corps', category: 'boxe', muscle: 'PUISSANCE', unit: 'time' },
  { name: 'Combinaisons (1-2)', category: 'boxe', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Combinaisons (1-2-3)', category: 'boxe', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Combinaisons (1-2-3-2)', category: 'boxe', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Jab (Technique)', category: 'boxe', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Cross (Technique)', category: 'boxe', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Crochet (Hook)', category: 'boxe', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Uppercut', category: 'boxe', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Overhand', category: 'boxe', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Body Shots', category: 'boxe', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Counter Punching', category: 'boxe', muscle: 'TACTIQUE', unit: 'time' },
  { name: 'Travail en Angle', category: 'boxe', muscle: 'TACTIQUE', unit: 'time' },
  { name: 'Clinch Work', category: 'boxe', muscle: 'TECHNIQUE', unit: 'time' },

  // ═══════════════════════════════════════════════════════════════
  // MMA (ARTS MARTIAUX MIXTES) - COMPLET
  // ═══════════════════════════════════════════════════════════════
  { name: 'MMA Sparring (Light)', category: 'mma', muscle: 'COMBAT', unit: 'time' },
  { name: 'MMA Sparring (Full)', category: 'mma', muscle: 'COMBAT', unit: 'time' },
  { name: 'Sparring Pieds-Poings', category: 'mma', muscle: 'STRIKING', unit: 'time' },
  { name: 'Wall Wrestling', category: 'mma', muscle: 'LUTTE', unit: 'time' },
  { name: 'Cage Work', category: 'mma', muscle: 'LUTTE', unit: 'time' },
  { name: 'Ground and Pound (Sac)', category: 'mma', muscle: 'FRAPPE', unit: 'time' },
  { name: 'Ground and Pound (Drills)', category: 'mma', muscle: 'FRAPPE', unit: 'reps' },
  { name: 'Transitions Striking/Wrestling', category: 'mma', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Clinch Dirty Boxing', category: 'mma', muscle: 'STRIKING', unit: 'time' },
  { name: 'Takedown Defense', category: 'mma', muscle: 'DÉFENSE', unit: 'reps' },
  { name: 'Sprawl & Brawl', category: 'mma', muscle: 'DÉFENSE', unit: 'reps' },
  { name: 'Get Up Drills', category: 'mma', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'MMA Combos (Striking)', category: 'mma', muscle: 'STRIKING', unit: 'reps' },
  { name: 'Submission Defense', category: 'mma', muscle: 'DÉFENSE', unit: 'time' },
  { name: 'Positional Grappling', category: 'mma', muscle: 'GRAPPLING', unit: 'time' },
  { name: 'Wrestling Drills', category: 'mma', muscle: 'LUTTE', unit: 'reps' },
  { name: 'Shadow MMA', category: 'mma', muscle: 'TECHNIQUE', unit: 'time' },
  { name: 'Pads MMA', category: 'mma', muscle: 'STRIKING', unit: 'time' },
  { name: 'Leg Kicks (Low/Mid/High)', category: 'mma', muscle: 'STRIKING', unit: 'reps' },
  { name: 'Knees in Clinch', category: 'mma', muscle: 'STRIKING', unit: 'reps' },
  { name: 'Elbows', category: 'mma', muscle: 'STRIKING', unit: 'reps' },
  { name: 'Submission Flow', category: 'mma', muscle: 'GRAPPLING', unit: 'time' },

  // ═══════════════════════════════════════════════════════════════
  // MUAY THAI - COMPLET
  // ═══════════════════════════════════════════════════════════════
  { name: 'Thai Pads (Pao)', category: 'muay_thai', muscle: 'INTENSITÉ', unit: 'time' },
  { name: 'Clinch / Corps à corps', category: 'muay_thai', muscle: 'TECHNIQUE', unit: 'time' },
  { name: 'Kick Rounds (Sac)', category: 'muay_thai', muscle: 'PUISSANCE', unit: 'reps' },
  { name: 'Shadow Muay Thai', category: 'muay_thai', muscle: 'TECHNIQUE', unit: 'time' },
  { name: 'Heavy Bag Thai', category: 'muay_thai', muscle: 'PUISSANCE', unit: 'time' },
  { name: 'Teep (Front Kick)', category: 'muay_thai', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Low Kick', category: 'muay_thai', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Body Kick', category: 'muay_thai', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Head Kick', category: 'muay_thai', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Switch Kick', category: 'muay_thai', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Question Mark Kick', category: 'muay_thai', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Elbow Techniques', category: 'muay_thai', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Knee Techniques', category: 'muay_thai', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Clinch Knees', category: 'muay_thai', muscle: 'CLINCH', unit: 'reps' },
  { name: 'Clinch Elbows', category: 'muay_thai', muscle: 'CLINCH', unit: 'reps' },
  { name: 'Dump (Clinch)', category: 'muay_thai', muscle: 'CLINCH', unit: 'reps' },
  { name: 'Sweep (Clinch)', category: 'muay_thai', muscle: 'CLINCH', unit: 'reps' },
  { name: 'Catch & Kick', category: 'muay_thai', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Check & Counter', category: 'muay_thai', muscle: 'DÉFENSE', unit: 'reps' },
  { name: 'Sparring Muay Thai', category: 'muay_thai', muscle: 'COMBAT', unit: 'time' },
  { name: 'Technical Sparring', category: 'muay_thai', muscle: 'COMBAT', unit: 'time' },
  { name: 'Clinch Sparring', category: 'muay_thai', muscle: 'COMBAT', unit: 'time' },
  { name: 'Conditioning Thai', category: 'muay_thai', muscle: 'CARDIO', unit: 'time' },

  // ═══════════════════════════════════════════════════════════════
  // JUDO - COMPLET
  // ═══════════════════════════════════════════════════════════════
  { name: 'Uchi-komi (Répétitions)', category: 'judo', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Randori (Combat)', category: 'judo', muscle: 'INTENSITÉ', unit: 'time' },
  { name: 'Nage-komi (Projections)', category: 'judo', muscle: 'PUISSANCE', unit: 'reps' },
  { name: 'Ne-waza (Sol)', category: 'judo', muscle: 'TECHNIQUE', unit: 'time' },
  { name: 'Kata', category: 'judo', muscle: 'FORME', unit: 'time' },
  // Projections de jambes (Ashi-waza)
  { name: 'O-soto-gari', category: 'judo', muscle: 'ASHI-WAZA', unit: 'reps' },
  { name: 'O-uchi-gari', category: 'judo', muscle: 'ASHI-WAZA', unit: 'reps' },
  { name: 'Ko-uchi-gari', category: 'judo', muscle: 'ASHI-WAZA', unit: 'reps' },
  { name: 'De-ashi-barai', category: 'judo', muscle: 'ASHI-WAZA', unit: 'reps' },
  { name: 'Sasae-tsurikomi-ashi', category: 'judo', muscle: 'ASHI-WAZA', unit: 'reps' },
  { name: 'Hiza-guruma', category: 'judo', muscle: 'ASHI-WAZA', unit: 'reps' },
  { name: 'Ashi-guruma', category: 'judo', muscle: 'ASHI-WAZA', unit: 'reps' },
  { name: 'Okuri-ashi-barai', category: 'judo', muscle: 'ASHI-WAZA', unit: 'reps' },
  { name: 'Harai-tsurikomi-ashi', category: 'judo', muscle: 'ASHI-WAZA', unit: 'reps' },
  // Projections de hanches (Koshi-waza)
  { name: 'O-goshi', category: 'judo', muscle: 'KOSHI-WAZA', unit: 'reps' },
  { name: 'Koshi-guruma', category: 'judo', muscle: 'KOSHI-WAZA', unit: 'reps' },
  { name: 'Harai-goshi', category: 'judo', muscle: 'KOSHI-WAZA', unit: 'reps' },
  { name: 'Uchi-mata', category: 'judo', muscle: 'KOSHI-WAZA', unit: 'reps' },
  { name: 'Hane-goshi', category: 'judo', muscle: 'KOSHI-WAZA', unit: 'reps' },
  { name: 'Uki-goshi', category: 'judo', muscle: 'KOSHI-WAZA', unit: 'reps' },
  { name: 'Tsuri-goshi', category: 'judo', muscle: 'KOSHI-WAZA', unit: 'reps' },
  { name: 'Tsurikomi-goshi', category: 'judo', muscle: 'KOSHI-WAZA', unit: 'reps' },
  { name: 'Sode-tsurikomi-goshi', category: 'judo', muscle: 'KOSHI-WAZA', unit: 'reps' },
  // Projections de bras (Te-waza)
  { name: 'Seoi-nage', category: 'judo', muscle: 'TE-WAZA', unit: 'reps' },
  { name: 'Ippon-seoi-nage', category: 'judo', muscle: 'TE-WAZA', unit: 'reps' },
  { name: 'Morote-seoi-nage', category: 'judo', muscle: 'TE-WAZA', unit: 'reps' },
  { name: 'Tai-otoshi', category: 'judo', muscle: 'TE-WAZA', unit: 'reps' },
  { name: 'Kata-guruma', category: 'judo', muscle: 'TE-WAZA', unit: 'reps' },
  { name: 'Sukui-nage', category: 'judo', muscle: 'TE-WAZA', unit: 'reps' },
  { name: 'Te-guruma', category: 'judo', muscle: 'TE-WAZA', unit: 'reps' },
  { name: 'Kouchi-gaeshi', category: 'judo', muscle: 'TE-WAZA', unit: 'reps' },
  // Sacrifices (Sutemi-waza)
  { name: 'Tomoe-nage', category: 'judo', muscle: 'SUTEMI-WAZA', unit: 'reps' },
  { name: 'Sumi-gaeshi', category: 'judo', muscle: 'SUTEMI-WAZA', unit: 'reps' },
  { name: 'Ura-nage', category: 'judo', muscle: 'SUTEMI-WAZA', unit: 'reps' },
  { name: 'Tani-otoshi', category: 'judo', muscle: 'SUTEMI-WAZA', unit: 'reps' },
  { name: 'Yoko-guruma', category: 'judo', muscle: 'SUTEMI-WAZA', unit: 'reps' },
  { name: 'Uki-waza', category: 'judo', muscle: 'SUTEMI-WAZA', unit: 'reps' },
  // Ne-waza (Sol)
  { name: 'Kesa-gatame', category: 'judo', muscle: 'NE-WAZA', unit: 'time' },
  { name: 'Yoko-shiho-gatame', category: 'judo', muscle: 'NE-WAZA', unit: 'time' },
  { name: 'Kami-shiho-gatame', category: 'judo', muscle: 'NE-WAZA', unit: 'time' },
  { name: 'Tate-shiho-gatame', category: 'judo', muscle: 'NE-WAZA', unit: 'time' },
  { name: 'Juji-gatame', category: 'judo', muscle: 'NE-WAZA', unit: 'reps' },
  { name: 'Ude-garami', category: 'judo', muscle: 'NE-WAZA', unit: 'reps' },
  { name: 'Sankaku-jime', category: 'judo', muscle: 'NE-WAZA', unit: 'reps' },
  { name: 'Hadaka-jime', category: 'judo', muscle: 'NE-WAZA', unit: 'reps' },
  { name: 'Okuri-eri-jime', category: 'judo', muscle: 'NE-WAZA', unit: 'reps' },

  // ═══════════════════════════════════════════════════════════════
  // LUTTE (WRESTLING) - COMPLET
  // ═══════════════════════════════════════════════════════════════
  { name: 'Shoot Drills', category: 'lutte', muscle: 'EXPLOSIVITÉ', unit: 'reps' },
  { name: 'Sprawl Drills', category: 'lutte', muscle: 'RÉACTION', unit: 'reps' },
  { name: 'Combat Libre', category: 'lutte', muscle: 'INTENSITÉ', unit: 'time' },
  { name: 'Lutte Gréco-Romaine', category: 'lutte', muscle: 'FORCE', unit: 'time' },
  { name: 'Chain Wrestling', category: 'lutte', muscle: 'TECHNIQUE', unit: 'time' },
  { name: 'Pummeling', category: 'lutte', muscle: 'TECHNIQUE', unit: 'time' },
  // Takedowns
  { name: 'Single Leg', category: 'lutte', muscle: 'TAKEDOWNS', unit: 'reps' },
  { name: 'Double Leg', category: 'lutte', muscle: 'TAKEDOWNS', unit: 'reps' },
  { name: 'High Crotch', category: 'lutte', muscle: 'TAKEDOWNS', unit: 'reps' },
  { name: 'Fireman\'s Carry', category: 'lutte', muscle: 'TAKEDOWNS', unit: 'reps' },
  { name: 'Ankle Pick', category: 'lutte', muscle: 'TAKEDOWNS', unit: 'reps' },
  { name: 'Arm Drag', category: 'lutte', muscle: 'TAKEDOWNS', unit: 'reps' },
  { name: 'Duck Under', category: 'lutte', muscle: 'TAKEDOWNS', unit: 'reps' },
  { name: 'Slide By', category: 'lutte', muscle: 'TAKEDOWNS', unit: 'reps' },
  { name: 'Snap Down', category: 'lutte', muscle: 'TAKEDOWNS', unit: 'reps' },
  { name: 'Front Headlock', category: 'lutte', muscle: 'TAKEDOWNS', unit: 'reps' },
  { name: 'Russian Tie', category: 'lutte', muscle: 'TAKEDOWNS', unit: 'reps' },
  { name: '2 on 1', category: 'lutte', muscle: 'TAKEDOWNS', unit: 'reps' },
  { name: 'Underhook Series', category: 'lutte', muscle: 'TAKEDOWNS', unit: 'reps' },
  { name: 'Collar Tie Attacks', category: 'lutte', muscle: 'TAKEDOWNS', unit: 'reps' },
  // Gréco-Romaine
  { name: 'Arm Throw', category: 'lutte', muscle: 'GRÉCO', unit: 'reps' },
  { name: 'Suplex', category: 'lutte', muscle: 'GRÉCO', unit: 'reps' },
  { name: 'Hip Toss', category: 'lutte', muscle: 'GRÉCO', unit: 'reps' },
  { name: 'Body Lock Takedown', category: 'lutte', muscle: 'GRÉCO', unit: 'reps' },
  { name: 'Lateral Drop', category: 'lutte', muscle: 'GRÉCO', unit: 'reps' },
  // Par Terre
  { name: 'Breakdown', category: 'lutte', muscle: 'PAR TERRE', unit: 'reps' },
  { name: 'Gut Wrench', category: 'lutte', muscle: 'PAR TERRE', unit: 'reps' },
  { name: 'Leg Riding', category: 'lutte', muscle: 'PAR TERRE', unit: 'time' },
  { name: 'Cradle', category: 'lutte', muscle: 'PAR TERRE', unit: 'reps' },
  { name: 'Half Nelson', category: 'lutte', muscle: 'PAR TERRE', unit: 'reps' },
  { name: 'Turk', category: 'lutte', muscle: 'PAR TERRE', unit: 'reps' },
  // Escapes
  { name: 'Stand Up (Escape)', category: 'lutte', muscle: 'ESCAPES', unit: 'reps' },
  { name: 'Sit Out', category: 'lutte', muscle: 'ESCAPES', unit: 'reps' },
  { name: 'Switch', category: 'lutte', muscle: 'ESCAPES', unit: 'reps' },
  { name: 'Granby Roll', category: 'lutte', muscle: 'ESCAPES', unit: 'reps' },
  { name: 'Peterson Roll', category: 'lutte', muscle: 'ESCAPES', unit: 'reps' },

  // ═══════════════════════════════════════════════════════════════
  // KICKBOXING - COMPLET
  // ═══════════════════════════════════════════════════════════════
  { name: 'Shadow Kickboxing', category: 'kickboxing', muscle: 'TECHNIQUE', unit: 'time' },
  { name: 'Heavy Bag Kickboxing', category: 'kickboxing', muscle: 'PUISSANCE', unit: 'time' },
  { name: 'Pads Kickboxing', category: 'kickboxing', muscle: 'PRÉCISION', unit: 'time' },
  { name: 'Sparring Kickboxing', category: 'kickboxing', muscle: 'COMBAT', unit: 'time' },
  { name: 'Front Kick (Teep)', category: 'kickboxing', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Roundhouse Kick', category: 'kickboxing', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Side Kick', category: 'kickboxing', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Hook Kick', category: 'kickboxing', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Axe Kick', category: 'kickboxing', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Spinning Back Kick', category: 'kickboxing', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Spinning Hook Kick', category: 'kickboxing', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Combos Pieds-Poings', category: 'kickboxing', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Leg Check Drills', category: 'kickboxing', muscle: 'DÉFENSE', unit: 'reps' },

  // ═══════════════════════════════════════════════════════════════
  // KARATE / TAEKWONDO - COMPLET
  // ═══════════════════════════════════════════════════════════════
  { name: 'Katas / Poomsae', category: 'karate', muscle: 'FORME', unit: 'time' },
  { name: 'Kihon (Bases)', category: 'karate', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Kumite (Combat)', category: 'karate', muscle: 'VITESSE', unit: 'time' },
  { name: 'Frappes Cibles (Pao)', category: 'karate', muscle: 'PRÉCISION', unit: 'reps' },
  { name: 'Gyaku-zuki (Reverse Punch)', category: 'karate', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Oi-zuki (Lunge Punch)', category: 'karate', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Mae-geri (Front Kick)', category: 'karate', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Mawashi-geri (Roundhouse)', category: 'karate', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Yoko-geri (Side Kick)', category: 'karate', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Ushiro-geri (Back Kick)', category: 'karate', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Ura-mawashi-geri (Hook Kick)', category: 'karate', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Tobi-geri (Jump Kick)', category: 'karate', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Age-uke (Rising Block)', category: 'karate', muscle: 'DÉFENSE', unit: 'reps' },
  { name: 'Soto-uke (Outside Block)', category: 'karate', muscle: 'DÉFENSE', unit: 'reps' },
  { name: 'Gedan-barai (Downward Block)', category: 'karate', muscle: 'DÉFENSE', unit: 'reps' },
  { name: 'Bunkai (Application)', category: 'karate', muscle: 'TECHNIQUE', unit: 'time' },
  { name: 'Makiwara', category: 'karate', muscle: 'PUISSANCE', unit: 'reps' },

  // ═══════════════════════════════════════════════════════════════
  // KRAV MAGA - COMPLET
  // ═══════════════════════════════════════════════════════════════
  { name: 'Self-Defense Drills', category: 'krav_maga', muscle: 'TECHNIQUE', unit: 'time' },
  { name: 'Combat Scenarios', category: 'krav_maga', muscle: 'INTENSITÉ', unit: 'time' },
  { name: 'Striking Combatives', category: 'krav_maga', muscle: 'FRAPPE', unit: 'reps' },
  { name: 'Choke Defense', category: 'krav_maga', muscle: 'DÉFENSE', unit: 'reps' },
  { name: 'Headlock Defense', category: 'krav_maga', muscle: 'DÉFENSE', unit: 'reps' },
  { name: 'Bear Hug Defense', category: 'krav_maga', muscle: 'DÉFENSE', unit: 'reps' },
  { name: 'Knife Defense', category: 'krav_maga', muscle: 'DÉFENSE', unit: 'reps' },
  { name: 'Gun Defense', category: 'krav_maga', muscle: 'DÉFENSE', unit: 'reps' },
  { name: 'Ground Defense', category: 'krav_maga', muscle: 'DÉFENSE', unit: 'time' },
  { name: 'Multiple Attackers', category: 'krav_maga', muscle: 'SCÉNARIO', unit: 'time' },
  { name: 'Stress Drills', category: 'krav_maga', muscle: 'MENTAL', unit: 'time' },
  { name: '360 Defense', category: 'krav_maga', muscle: 'DÉFENSE', unit: 'reps' },
  { name: 'Inside Defense', category: 'krav_maga', muscle: 'DÉFENSE', unit: 'reps' },
  { name: 'Combatives (Palm Strike)', category: 'krav_maga', muscle: 'FRAPPE', unit: 'reps' },
  { name: 'Combatives (Hammer Fist)', category: 'krav_maga', muscle: 'FRAPPE', unit: 'reps' },
  { name: 'Combatives (Elbow)', category: 'krav_maga', muscle: 'FRAPPE', unit: 'reps' },
  { name: 'Combatives (Knee)', category: 'krav_maga', muscle: 'FRAPPE', unit: 'reps' },
  { name: 'Combatives (Kick)', category: 'krav_maga', muscle: 'FRAPPE', unit: 'reps' },

  // ═══════════════════════════════════════════════════════════════
  // CROSSFIT / WOD - COMPLET
  // ═══════════════════════════════════════════════════════════════
  { name: 'Kettlebell Swings', category: 'crossfit', muscle: 'CHAÎNE POST.', unit: 'reps' },
  { name: 'Box Jumps', category: 'crossfit', muscle: 'EXPLOSIVITÉ', unit: 'reps' },
  { name: 'Wall Balls', category: 'crossfit', muscle: 'CORPS ENTIER', unit: 'reps' },
  { name: 'Double Unders', category: 'crossfit', muscle: 'COORDINATION', unit: 'reps' },
  { name: 'Toes to Bar', category: 'crossfit', muscle: 'ABDOS', unit: 'reps' },
  { name: 'Clean & Jerk', category: 'crossfit', muscle: 'PUISSANCE', unit: 'reps' },
  { name: 'Snatch', category: 'crossfit', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Power Clean', category: 'crossfit', muscle: 'PUISSANCE', unit: 'reps' },
  { name: 'Hang Clean', category: 'crossfit', muscle: 'PUISSANCE', unit: 'reps' },
  { name: 'Power Snatch', category: 'crossfit', muscle: 'PUISSANCE', unit: 'reps' },
  { name: 'Hang Snatch', category: 'crossfit', muscle: 'PUISSANCE', unit: 'reps' },
  { name: 'Overhead Squat', category: 'crossfit', muscle: 'MOBILITÉ', unit: 'reps' },
  { name: 'Front Squat (CrossFit)', category: 'crossfit', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Thruster', category: 'crossfit', muscle: 'CORPS ENTIER', unit: 'reps' },
  { name: 'Push Press', category: 'crossfit', muscle: 'ÉPAULES', unit: 'reps' },
  { name: 'Push Jerk', category: 'crossfit', muscle: 'ÉPAULES', unit: 'reps' },
  { name: 'Split Jerk', category: 'crossfit', muscle: 'ÉPAULES', unit: 'reps' },
  { name: 'Burpees', category: 'crossfit', muscle: 'CARDIO', unit: 'reps' },
  { name: 'Burpee Box Jumps', category: 'crossfit', muscle: 'CARDIO', unit: 'reps' },
  { name: 'Burpee Pull-ups', category: 'crossfit', muscle: 'CARDIO', unit: 'reps' },
  { name: 'Muscle-ups (Ring)', category: 'crossfit', muscle: 'GYMNASTIQUE', unit: 'reps' },
  { name: 'Muscle-ups (Bar)', category: 'crossfit', muscle: 'GYMNASTIQUE', unit: 'reps' },
  { name: 'Pull-ups (Kipping)', category: 'crossfit', muscle: 'GYMNASTIQUE', unit: 'reps' },
  { name: 'Chest to Bar', category: 'crossfit', muscle: 'GYMNASTIQUE', unit: 'reps' },
  { name: 'Handstand Walk', category: 'crossfit', muscle: 'GYMNASTIQUE', unit: 'meters' },
  { name: 'Handstand Push-ups (Strict)', category: 'crossfit', muscle: 'GYMNASTIQUE', unit: 'reps' },
  { name: 'Handstand Push-ups (Kipping)', category: 'crossfit', muscle: 'GYMNASTIQUE', unit: 'reps' },
  { name: 'Ring Dips', category: 'crossfit', muscle: 'GYMNASTIQUE', unit: 'reps' },
  { name: 'Rope Climb', category: 'crossfit', muscle: 'GYMNASTIQUE', unit: 'reps' },
  { name: 'Rope Climb (Legless)', category: 'crossfit', muscle: 'GYMNASTIQUE', unit: 'reps' },
  { name: 'Pistols', category: 'crossfit', muscle: 'JAMBES', unit: 'reps' },
  { name: 'GHD Sit-ups', category: 'crossfit', muscle: 'ABDOS', unit: 'reps' },
  { name: 'GHD Hip Extensions', category: 'crossfit', muscle: 'CHAÎNE POST.', unit: 'reps' },
  { name: 'Turkish Get-up', category: 'crossfit', muscle: 'MOBILITÉ', unit: 'reps' },
  { name: 'KB Snatch', category: 'crossfit', muscle: 'PUISSANCE', unit: 'reps' },
  { name: 'KB Clean', category: 'crossfit', muscle: 'PUISSANCE', unit: 'reps' },
  { name: 'Devil Press', category: 'crossfit', muscle: 'CORPS ENTIER', unit: 'reps' },
  { name: 'Dumbbell Snatch', category: 'crossfit', muscle: 'PUISSANCE', unit: 'reps' },
  { name: 'Dumbbell Clean & Jerk', category: 'crossfit', muscle: 'PUISSANCE', unit: 'reps' },
  { name: 'Med Ball Clean', category: 'crossfit', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Sumo Deadlift High Pull', category: 'crossfit', muscle: 'PUISSANCE', unit: 'reps' },
  { name: 'Air Squat', category: 'crossfit', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Assault Bike (Cal)', category: 'crossfit', muscle: 'CARDIO', unit: 'reps' },
  { name: 'Row (Cal)', category: 'crossfit', muscle: 'CARDIO', unit: 'reps' },
  { name: 'SkiErg (Cal)', category: 'crossfit', muscle: 'CARDIO', unit: 'reps' },
  { name: 'Running (CrossFit)', category: 'crossfit', muscle: 'CARDIO', unit: 'meters' },

  // ═══════════════════════════════════════════════════════════════
  // RUNNING - COMPLET
  // ═══════════════════════════════════════════════════════════════
  { name: 'Footing Endurance', category: 'running', muscle: 'ENDURANCE', unit: 'km' },
  { name: 'Sortie Longue', category: 'running', muscle: 'ENDURANCE', unit: 'km' },
  { name: 'Fractionné Court (200m-400m)', category: 'running', muscle: 'VITESSE', unit: 'reps' },
  { name: 'Fractionné Moyen (800m-1000m)', category: 'running', muscle: 'VITESSE', unit: 'reps' },
  { name: 'Fractionné Long (2000m-3000m)', category: 'running', muscle: 'SEUIL', unit: 'reps' },
  { name: 'Tempo Run', category: 'running', muscle: 'SEUIL', unit: 'km' },
  { name: 'Fartlek', category: 'running', muscle: 'MIXTE', unit: 'time' },
  { name: 'Côtes (Hill Repeats)', category: 'running', muscle: 'FORCE', unit: 'reps' },
  { name: 'Récupération Active', category: 'running', muscle: 'RÉCUP', unit: 'km' },
  { name: 'Tapis Incliné', category: 'running', muscle: 'FORCE', unit: 'time' },
  { name: '5K Race Pace', category: 'running', muscle: 'COMPÉTITION', unit: 'km' },
  { name: '10K Race Pace', category: 'running', muscle: 'COMPÉTITION', unit: 'km' },
  { name: 'Semi-Marathon Pace', category: 'running', muscle: 'COMPÉTITION', unit: 'km' },
  { name: 'Marathon Pace', category: 'running', muscle: 'COMPÉTITION', unit: 'km' },
  { name: 'Sprint (100m)', category: 'running', muscle: 'VITESSE', unit: 'reps' },
  { name: 'Sprint (200m)', category: 'running', muscle: 'VITESSE', unit: 'reps' },
  { name: 'Sprint (400m)', category: 'running', muscle: 'VITESSE', unit: 'reps' },
  { name: 'Progressif', category: 'running', muscle: 'TECHNIQUE', unit: 'km' },
  { name: 'Negative Split', category: 'running', muscle: 'TACTIQUE', unit: 'km' },
  { name: 'Easy Run', category: 'running', muscle: 'RÉCUP', unit: 'km' },

  // ═══════════════════════════════════════════════════════════════
  // TRAIL - COMPLET
  // ═══════════════════════════════════════════════════════════════
  { name: 'Sortie Trail', category: 'trail', muscle: 'ENDURANCE', unit: 'km' },
  { name: 'Trail Technique', category: 'trail', muscle: 'TECHNIQUE', unit: 'km' },
  { name: 'Dénivelé Positif', category: 'trail', muscle: 'D+', unit: 'meters' },
  { name: 'Descente Technique', category: 'trail', muscle: 'TECHNIQUE', unit: 'km' },
  { name: 'Sortie Montagne', category: 'trail', muscle: 'ALTITUDE', unit: 'km' },
  { name: 'Ultra Endurance', category: 'trail', muscle: 'ENDURANCE', unit: 'km' },
  { name: 'Rando-Course', category: 'trail', muscle: 'MIXTE', unit: 'km' },
  { name: 'Entraînement Bâtons', category: 'trail', muscle: 'TECHNIQUE', unit: 'time' },
  { name: 'Simulation Course', category: 'trail', muscle: 'COMPÉTITION', unit: 'km' },

  // ═══════════════════════════════════════════════════════════════
  // CYCLISME / VÉLO - COMPLET
  // ═══════════════════════════════════════════════════════════════
  { name: 'Sortie Route (Endurance)', category: 'velo', muscle: 'JAMBES', unit: 'km' },
  { name: 'Sortie Récupération', category: 'velo', muscle: 'RÉCUP', unit: 'km' },
  { name: 'Fractionné Vélo', category: 'velo', muscle: 'PUISSANCE', unit: 'time' },
  { name: 'Sprint Cycliste', category: 'velo', muscle: 'PUISSANCE', unit: 'time' },
  { name: 'Montée de Col', category: 'velo', muscle: 'RÉSISTANCE', unit: 'km' },
  { name: 'CLM (Contre-la-Montre)', category: 'velo', muscle: 'EFFORT', unit: 'km' },
  { name: 'Home Trainer', category: 'velo', muscle: 'CARDIO', unit: 'time' },
  { name: 'Zwift / Virtual', category: 'velo', muscle: 'CARDIO', unit: 'km' },
  { name: 'Sweet Spot Training', category: 'velo', muscle: 'SEUIL', unit: 'time' },
  { name: 'FTP Test', category: 'velo', muscle: 'TEST', unit: 'time' },
  { name: 'Over-Under Intervals', category: 'velo', muscle: 'SEUIL', unit: 'time' },
  { name: 'VO2 Max Intervals', category: 'velo', muscle: 'INTENSITÉ', unit: 'reps' },
  { name: 'Cadence Work', category: 'velo', muscle: 'TECHNIQUE', unit: 'time' },
  { name: 'Force (Braquet Lourd)', category: 'velo', muscle: 'FORCE', unit: 'time' },
  { name: 'Vélocité (Cadence Haute)', category: 'velo', muscle: 'TECHNIQUE', unit: 'time' },

  // ═══════════════════════════════════════════════════════════════
  // NATATION - COMPLET
  // ═══════════════════════════════════════════════════════════════
  { name: 'Crawl (Freestyle)', category: 'natation', muscle: 'CORPS ENTIER', unit: 'km' },
  { name: 'Dos Crawlé', category: 'natation', muscle: 'DOS', unit: 'km' },
  { name: 'Brasse', category: 'natation', muscle: 'JAMBES', unit: 'km' },
  { name: 'Papillon', category: 'natation', muscle: 'PUISSANCE', unit: 'km' },
  { name: '4 Nages', category: 'natation', muscle: 'COMPLET', unit: 'km' },
  { name: 'Éducatifs Crawl', category: 'natation', muscle: 'TECHNIQUE', unit: 'meters' },
  { name: 'Éducatifs Dos', category: 'natation', muscle: 'TECHNIQUE', unit: 'meters' },
  { name: 'Éducatifs Brasse', category: 'natation', muscle: 'TECHNIQUE', unit: 'meters' },
  { name: 'Éducatifs Papillon', category: 'natation', muscle: 'TECHNIQUE', unit: 'meters' },
  { name: 'Pull Buoy', category: 'natation', muscle: 'BRAS', unit: 'meters' },
  { name: 'Plaquettes', category: 'natation', muscle: 'PUISSANCE', unit: 'meters' },
  { name: 'Palmes', category: 'natation', muscle: 'JAMBES', unit: 'meters' },
  { name: 'Battements', category: 'natation', muscle: 'JAMBES', unit: 'meters' },
  { name: 'Séries Vitesse', category: 'natation', muscle: 'EXPLOSIVITÉ', unit: 'meters' },
  { name: 'Endurance Natation', category: 'natation', muscle: 'ENDURANCE', unit: 'km' },
  { name: 'Eau Libre', category: 'natation', muscle: 'ENDURANCE', unit: 'km' },
  { name: 'Apnée Statique', category: 'natation', muscle: 'SOUFFLE', unit: 'time' },
  { name: 'Apnée Dynamique', category: 'natation', muscle: 'SOUFFLE', unit: 'meters' },
  { name: 'Ondulations', category: 'natation', muscle: 'TECHNIQUE', unit: 'meters' },
  { name: 'Départs', category: 'natation', muscle: 'EXPLOSIVITÉ', unit: 'reps' },
  { name: 'Virages', category: 'natation', muscle: 'TECHNIQUE', unit: 'reps' },

  // ═══════════════════════════════════════════════════════════════
  // YOGA / PILATES / STRETCHING
  // ═══════════════════════════════════════════════════════════════
  { name: 'Salutation au Soleil', category: 'yoga', muscle: 'FLOW', unit: 'reps' },
  { name: 'Vinyasa Flow', category: 'yoga', muscle: 'FLOW', unit: 'time' },
  { name: 'Hatha Yoga', category: 'yoga', muscle: 'POSTURES', unit: 'time' },
  { name: 'Ashtanga Yoga', category: 'yoga', muscle: 'SÉRIES', unit: 'time' },
  { name: 'Yin Yoga', category: 'yoga', muscle: 'ÉTIREMENTS', unit: 'time' },
  { name: 'Power Yoga', category: 'yoga', muscle: 'FORCE', unit: 'time' },
  { name: 'Yoga Restauratif', category: 'yoga', muscle: 'RÉCUP', unit: 'time' },
  { name: 'Hot Yoga', category: 'yoga', muscle: 'ENDURANCE', unit: 'time' },
  { name: 'Pilates Mat', category: 'pilates', muscle: 'CORE', unit: 'time' },
  { name: 'Pilates Reformer', category: 'pilates', muscle: 'CORE', unit: 'time' },
  { name: 'Pilates Hundred', category: 'pilates', muscle: 'ABDOS', unit: 'reps' },
  { name: 'Pilates Roll Up', category: 'pilates', muscle: 'ABDOS', unit: 'reps' },
  { name: 'Stretching Global', category: 'stretching', muscle: 'FLEXIBILITÉ', unit: 'time' },
  { name: 'Stretching Haut du Corps', category: 'stretching', muscle: 'FLEXIBILITÉ', unit: 'time' },
  { name: 'Stretching Bas du Corps', category: 'stretching', muscle: 'FLEXIBILITÉ', unit: 'time' },
  { name: 'Stretching Dos', category: 'stretching', muscle: 'FLEXIBILITÉ', unit: 'time' },
  { name: 'Foam Rolling', category: 'stretching', muscle: 'RÉCUP', unit: 'time' },
  { name: 'Mobilité Épaules', category: 'stretching', muscle: 'MOBILITÉ', unit: 'time' },
  { name: 'Mobilité Hanches', category: 'stretching', muscle: 'MOBILITÉ', unit: 'time' },
  { name: 'Mobilité Chevilles', category: 'stretching', muscle: 'MOBILITÉ', unit: 'time' },
  { name: 'Mobilité Thoracique', category: 'stretching', muscle: 'MOBILITÉ', unit: 'time' },

  // ═══════════════════════════════════════════════════════════════
  // HIIT
  // ═══════════════════════════════════════════════════════════════
  { name: 'HIIT Circuit', category: 'hiit', muscle: 'FULL BODY', unit: 'time' },
  { name: 'Tabata', category: 'hiit', muscle: 'INTENSITÉ', unit: 'time' },
  { name: 'EMOM', category: 'hiit', muscle: 'MIXTE', unit: 'time' },
  { name: 'AMRAP', category: 'hiit', muscle: 'MIXTE', unit: 'time' },
  { name: 'Chipper', category: 'hiit', muscle: 'ENDURANCE', unit: 'time' },
  { name: 'Ladder', category: 'hiit', muscle: 'PROGRESSIF', unit: 'time' },
  { name: 'Sprint Intervals', category: 'hiit', muscle: 'CARDIO', unit: 'time' },
  { name: 'Battle Ropes', category: 'hiit', muscle: 'BRAS', unit: 'time' },
  { name: 'Slam Ball', category: 'hiit', muscle: 'PUISSANCE', unit: 'reps' },
  { name: 'Box Jumps HIIT', category: 'hiit', muscle: 'EXPLOSIVITÉ', unit: 'reps' },
  { name: 'Burpees HIIT', category: 'hiit', muscle: 'CARDIO', unit: 'reps' },
  { name: 'Mountain Climbers HIIT', category: 'hiit', muscle: 'CARDIO', unit: 'time' },
  { name: 'Jump Squats', category: 'hiit', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Jump Lunges', category: 'hiit', muscle: 'JAMBES', unit: 'reps' },
  { name: 'High Knees', category: 'hiit', muscle: 'CARDIO', unit: 'time' },
  { name: 'Jumping Jacks', category: 'hiit', muscle: 'CARDIO', unit: 'reps' },
  { name: 'Plyo Push-ups', category: 'hiit', muscle: 'POITRINE', unit: 'reps' },
  { name: 'Tuck Jumps', category: 'hiit', muscle: 'EXPLOSIVITÉ', unit: 'reps' },

  // ═══════════════════════════════════════════════════════════════
  // SPORTS COLLECTIFS
  // ═══════════════════════════════════════════════════════════════
  { name: 'Match Football', category: 'football', muscle: 'MATCH', unit: 'time' },
  { name: 'Entraînement Football', category: 'football', muscle: 'TRAINING', unit: 'time' },
  { name: 'Possession', category: 'football', muscle: 'TECHNIQUE', unit: 'time' },
  { name: 'Exercices Passes', category: 'football', muscle: 'TECHNIQUE', unit: 'time' },
  { name: 'Exercices Tirs', category: 'football', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Dribbles', category: 'football', muscle: 'TECHNIQUE', unit: 'time' },
  { name: 'Match Basketball', category: 'basketball', muscle: 'MATCH', unit: 'time' },
  { name: 'Entraînement Basketball', category: 'basketball', muscle: 'TRAINING', unit: 'time' },
  { name: 'Tirs 3 Points', category: 'basketball', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Lay-ups', category: 'basketball', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Dribble Drills', category: 'basketball', muscle: 'TECHNIQUE', unit: 'time' },
  { name: 'Match Rugby', category: 'rugby', muscle: 'MATCH', unit: 'time' },
  { name: 'Entraînement Rugby', category: 'rugby', muscle: 'TRAINING', unit: 'time' },
  { name: 'Mêlées', category: 'rugby', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Touches', category: 'rugby', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Plaquages', category: 'rugby', muscle: 'TECHNIQUE', unit: 'reps' },

  // ═══════════════════════════════════════════════════════════════
  // SPORTS DE RAQUETTE
  // ═══════════════════════════════════════════════════════════════
  { name: 'Match Tennis', category: 'tennis', muscle: 'MATCH', unit: 'time' },
  { name: 'Entraînement Tennis', category: 'tennis', muscle: 'TRAINING', unit: 'time' },
  { name: 'Service', category: 'tennis', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Coups Droits', category: 'tennis', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Revers', category: 'tennis', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Volées', category: 'tennis', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Match Padel', category: 'padel', muscle: 'MATCH', unit: 'time' },
  { name: 'Entraînement Padel', category: 'padel', muscle: 'TRAINING', unit: 'time' },
  { name: 'Smash Padel', category: 'padel', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Bandeja', category: 'padel', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Vibora', category: 'padel', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Match Badminton', category: 'badminton', muscle: 'MATCH', unit: 'time' },
  { name: 'Entraînement Badminton', category: 'badminton', muscle: 'TRAINING', unit: 'time' },
  { name: 'Smash Badminton', category: 'badminton', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Clear', category: 'badminton', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Drop Shot', category: 'badminton', muscle: 'TECHNIQUE', unit: 'reps' },

  // ═══════════════════════════════════════════════════════════════
  // ESCALADE
  // ═══════════════════════════════════════════════════════════════
  { name: 'Bloc (Bouldering)', category: 'escalade', muscle: 'VOIES', unit: 'reps' },
  { name: 'Voie (Lead)', category: 'escalade', muscle: 'VOIES', unit: 'reps' },
  { name: 'Moulinette (Top Rope)', category: 'escalade', muscle: 'VOIES', unit: 'reps' },
  { name: 'Pan Gullich', category: 'escalade', muscle: 'FORCE', unit: 'time' },
  { name: 'Campus Board', category: 'escalade', muscle: 'FORCE', unit: 'time' },
  { name: 'Poutre (Hangboard)', category: 'escalade', muscle: 'FORCE', unit: 'time' },
  { name: 'Suspensions', category: 'escalade', muscle: 'FORCE', unit: 'time' },
  { name: 'Traversée', category: 'escalade', muscle: 'ENDURANCE', unit: 'time' },
  { name: 'Projets', category: 'escalade', muscle: 'TECHNIQUE', unit: 'time' },
  { name: 'Technique Pieds', category: 'escalade', muscle: 'TECHNIQUE', unit: 'time' },

  // ═══════════════════════════════════════════════════════════════
  // EXERCICES SUPPLÉMENTAIRES - MUSCULATION AVANCÉE
  // ═══════════════════════════════════════════════════════════════
  { name: 'Bench Press Pause', category: 'musculation', muscle: 'PECTORAUX', unit: 'reps' },
  { name: 'Spoto Press', category: 'musculation', muscle: 'PECTORAUX', unit: 'reps' },
  { name: 'Larsen Press', category: 'musculation', muscle: 'PECTORAUX', unit: 'reps' },
  { name: 'Guillotine Press', category: 'musculation', muscle: 'PECTORAUX', unit: 'reps' },
  { name: 'Svend Press', category: 'musculation', muscle: 'PECTORAUX', unit: 'reps' },
  { name: 'Hex Press', category: 'musculation', muscle: 'PECTORAUX', unit: 'reps' },
  { name: 'Cable Crossover', category: 'musculation', muscle: 'PECTORAUX', unit: 'reps' },
  { name: 'Incline Cable Fly', category: 'musculation', muscle: 'PECTORAUX', unit: 'reps' },
  { name: 'Deficit Push-ups', category: 'musculation', muscle: 'PECTORAUX', unit: 'reps' },
  { name: 'Pike Push-ups', category: 'musculation', muscle: 'PECTORAUX', unit: 'reps' },
  { name: 'Archer Push-ups', category: 'musculation', muscle: 'PECTORAUX', unit: 'reps' },
  { name: 'Snatch Grip Deadlift', category: 'musculation', muscle: 'DOS', unit: 'reps' },
  { name: 'Jefferson Deadlift', category: 'musculation', muscle: 'DOS', unit: 'reps' },
  { name: 'Trap Bar Deadlift', category: 'musculation', muscle: 'DOS', unit: 'reps' },
  { name: 'Deficit Deadlift', category: 'musculation', muscle: 'DOS', unit: 'reps' },
  { name: 'Block Pull', category: 'musculation', muscle: 'DOS', unit: 'reps' },
  { name: 'Rack Pull', category: 'musculation', muscle: 'DOS', unit: 'reps' },
  { name: 'Kroc Row', category: 'musculation', muscle: 'DOS', unit: 'reps' },
  { name: 'Helms Row', category: 'musculation', muscle: 'DOS', unit: 'reps' },
  { name: 'Chest Supported Row', category: 'musculation', muscle: 'DOS', unit: 'reps' },
  { name: 'Inverted Row', category: 'musculation', muscle: 'DOS', unit: 'reps' },
  { name: 'Ring Row', category: 'musculation', muscle: 'DOS', unit: 'reps' },
  { name: 'Meadows Row (Landmine)', category: 'musculation', muscle: 'DOS', unit: 'reps' },
  { name: 'Single Arm Lat Pulldown', category: 'musculation', muscle: 'DOS', unit: 'reps' },
  { name: 'Straight Arm Pulldown', category: 'musculation', muscle: 'DOS', unit: 'reps' },
  { name: 'Z-Press', category: 'musculation', muscle: 'ÉPAULES', unit: 'reps' },
  { name: 'Viking Press', category: 'musculation', muscle: 'ÉPAULES', unit: 'reps' },
  { name: 'Landmine Press (Épaules)', category: 'musculation', muscle: 'ÉPAULES', unit: 'reps' },
  { name: 'Cable Lateral Raise', category: 'musculation', muscle: 'ÉPAULES', unit: 'reps' },
  { name: 'Leaning Lateral Raise', category: 'musculation', muscle: 'ÉPAULES', unit: 'reps' },
  { name: 'Prone Y Raise', category: 'musculation', muscle: 'ÉPAULES', unit: 'reps' },
  { name: 'Prone T Raise', category: 'musculation', muscle: 'ÉPAULES', unit: 'reps' },
  { name: 'Prone W Raise', category: 'musculation', muscle: 'ÉPAULES', unit: 'reps' },
  { name: 'Behind Neck Press', category: 'musculation', muscle: 'ÉPAULES', unit: 'reps' },
  { name: 'Machine Lateral Raise', category: 'musculation', muscle: 'ÉPAULES', unit: 'reps' },
  { name: 'Scott Press', category: 'musculation', muscle: 'ÉPAULES', unit: 'reps' },
  { name: 'Bus Driver', category: 'musculation', muscle: 'ÉPAULES', unit: 'reps' },
  { name: 'Spider Curl', category: 'musculation', muscle: 'BICEPS', unit: 'reps' },
  { name: 'Cable Curl', category: 'musculation', muscle: 'BICEPS', unit: 'reps' },
  { name: 'Bayesian Curl', category: 'musculation', muscle: 'BICEPS', unit: 'reps' },
  { name: 'Cross Body Curl', category: 'musculation', muscle: 'BICEPS', unit: 'reps' },
  { name: 'Waiter Curl', category: 'musculation', muscle: 'BICEPS', unit: 'reps' },
  { name: 'Prone Incline Curl', category: 'musculation', muscle: 'BICEPS', unit: 'reps' },
  { name: 'Overhead Triceps Extension', category: 'musculation', muscle: 'TRICEPS', unit: 'reps' },
  { name: 'Cable Overhead Extension', category: 'musculation', muscle: 'TRICEPS', unit: 'reps' },
  { name: 'Single Arm Pushdown', category: 'musculation', muscle: 'TRICEPS', unit: 'reps' },
  { name: 'Reverse Grip Pushdown', category: 'musculation', muscle: 'TRICEPS', unit: 'reps' },
  { name: 'Tate Press', category: 'musculation', muscle: 'TRICEPS', unit: 'reps' },
  { name: 'Rolling Triceps Extension', category: 'musculation', muscle: 'TRICEPS', unit: 'reps' },
  { name: 'French Press', category: 'musculation', muscle: 'TRICEPS', unit: 'reps' },
  { name: 'Safety Bar Squat', category: 'musculation', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Belt Squat', category: 'musculation', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Anderson Squat', category: 'musculation', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Pause Squat', category: 'musculation', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Pin Squat', category: 'musculation', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Single Leg Press', category: 'musculation', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Leg Press (Narrow)', category: 'musculation', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Leg Press (Wide)', category: 'musculation', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Split Squat', category: 'musculation', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Cyclist Squat', category: 'musculation', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Spanish Squat', category: 'musculation', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Reverse Nordic', category: 'musculation', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Leg Extension (Single)', category: 'musculation', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Seated Leg Curl', category: 'musculation', muscle: 'ISCHIOS', unit: 'reps' },
  { name: 'Lying Leg Curl (Single)', category: 'musculation', muscle: 'ISCHIOS', unit: 'reps' },
  { name: 'Hip Hinge Machine', category: 'musculation', muscle: 'ISCHIOS', unit: 'reps' },
  { name: 'B-Stance RDL', category: 'musculation', muscle: 'ISCHIOS', unit: 'reps' },
  { name: 'Stiff Leg Deadlift', category: 'musculation', muscle: 'ISCHIOS', unit: 'reps' },
  { name: 'Frog Pump', category: 'musculation', muscle: 'FESSIERS', unit: 'reps' },
  { name: 'B-Stance Hip Thrust', category: 'musculation', muscle: 'FESSIERS', unit: 'reps' },
  { name: 'Kas Glute Bridge', category: 'musculation', muscle: 'FESSIERS', unit: 'reps' },
  { name: 'Cable Kickback', category: 'musculation', muscle: 'FESSIERS', unit: 'reps' },
  { name: 'Standing Kickback', category: 'musculation', muscle: 'FESSIERS', unit: 'reps' },
  { name: 'Monster Walk', category: 'musculation', muscle: 'FESSIERS', unit: 'reps' },
  { name: 'Lateral Band Walk', category: 'musculation', muscle: 'FESSIERS', unit: 'reps' },
  { name: 'Smith Machine Hip Thrust', category: 'musculation', muscle: 'FESSIERS', unit: 'reps' },
  { name: 'Standing Calf Raise', category: 'musculation', muscle: 'MOLLETS', unit: 'reps' },
  { name: 'Single Leg Calf Raise', category: 'musculation', muscle: 'MOLLETS', unit: 'reps' },
  { name: 'Leg Press Calf Raise', category: 'musculation', muscle: 'MOLLETS', unit: 'reps' },
  { name: 'Seated Calf Raise', category: 'musculation', muscle: 'MOLLETS', unit: 'reps' },
  { name: 'Cable Crunch', category: 'musculation', muscle: 'ABDOS', unit: 'reps' },
  { name: 'Decline Crunch', category: 'musculation', muscle: 'ABDOS', unit: 'reps' },
  { name: 'Hanging Knee Raise', category: 'musculation', muscle: 'ABDOS', unit: 'reps' },
  { name: 'Captain Chair', category: 'musculation', muscle: 'ABDOS', unit: 'reps' },
  { name: 'Ab Rollout', category: 'musculation', muscle: 'ABDOS', unit: 'reps' },
  { name: 'Ab Machine', category: 'musculation', muscle: 'ABDOS', unit: 'reps' },
  { name: 'Landmine Rotation', category: 'musculation', muscle: 'ABDOS', unit: 'reps' },
  { name: 'Side Bend', category: 'musculation', muscle: 'ABDOS', unit: 'reps' },
  { name: 'Weighted Plank', category: 'musculation', muscle: 'ABDOS', unit: 'time' },
  { name: 'Copenhagen Plank', category: 'musculation', muscle: 'ABDOS', unit: 'time' },
  { name: 'Long Lever Plank', category: 'musculation', muscle: 'ABDOS', unit: 'time' },
  { name: 'RKC Plank', category: 'musculation', muscle: 'ABDOS', unit: 'time' },

  // ═══════════════════════════════════════════════════════════════
  // EXERCICES SUPPLÉMENTAIRES - JJB AVANCÉ
  // ═══════════════════════════════════════════════════════════════
  { name: 'Imanari Roll', category: 'jjb', muscle: 'LEG LOCKS', unit: 'reps' },
  { name: 'Inside Sankaku', category: 'jjb', muscle: 'LEG LOCKS', unit: 'reps' },
  { name: 'Outside Sankaku', category: 'jjb', muscle: 'LEG LOCKS', unit: 'reps' },
  { name: 'Saddle Position', category: 'jjb', muscle: 'LEG LOCKS', unit: 'time' },
  { name: 'Ashi Garami', category: 'jjb', muscle: 'LEG LOCKS', unit: 'time' },
  { name: 'Cross Ashi', category: 'jjb', muscle: 'LEG LOCKS', unit: 'time' },
  { name: '411 Position', category: 'jjb', muscle: 'LEG LOCKS', unit: 'time' },
  { name: 'Honeyhole', category: 'jjb', muscle: 'LEG LOCKS', unit: 'time' },
  { name: 'Game Over Position', category: 'jjb', muscle: 'LEG LOCKS', unit: 'time' },
  { name: 'Matrix (DLR)', category: 'jjb', muscle: 'GARDES', unit: 'time' },
  { name: 'Mantis Guard', category: 'jjb', muscle: 'GARDES', unit: 'time' },
  { name: 'Lapel Guard', category: 'jjb', muscle: 'GARDES', unit: 'time' },
  { name: 'Deep Half Guard', category: 'jjb', muscle: 'GARDES', unit: 'time' },
  { name: 'Lockdown (Half)', category: 'jjb', muscle: 'GARDES', unit: 'time' },
  { name: 'No-Gi Collar Tie', category: 'jjb', muscle: 'LUTTE', unit: 'time' },
  { name: 'Over/Under Control', category: 'jjb', muscle: 'LUTTE', unit: 'time' },
  { name: 'Clinch Pummeling', category: 'jjb', muscle: 'LUTTE', unit: 'time' },
  { name: 'Body Lock (Standing)', category: 'jjb', muscle: 'LUTTE', unit: 'reps' },
  { name: 'Float Pass', category: 'jjb', muscle: 'PASSAGES', unit: 'reps' },
  { name: 'Hip Switch Pass', category: 'jjb', muscle: 'PASSAGES', unit: 'reps' },
  { name: 'Tripod Pass', category: 'jjb', muscle: 'PASSAGES', unit: 'reps' },
  { name: 'Folding Pass', category: 'jjb', muscle: 'PASSAGES', unit: 'reps' },
  { name: 'Guillotine Pass', category: 'jjb', muscle: 'PASSAGES', unit: 'reps' },
  { name: 'Collar Drag Sweep', category: 'jjb', muscle: 'SWEEPS', unit: 'reps' },
  { name: 'Old School Sweep', category: 'jjb', muscle: 'SWEEPS', unit: 'reps' },
  { name: 'Plan B Sweep', category: 'jjb', muscle: 'SWEEPS', unit: 'reps' },
  { name: 'Dummy Sweep', category: 'jjb', muscle: 'SWEEPS', unit: 'reps' },
  { name: 'Technical Stand Up', category: 'jjb', muscle: 'ESCAPES', unit: 'reps' },
  { name: 'Granby Roll', category: 'jjb', muscle: 'ESCAPES', unit: 'reps' },
  { name: 'Sit Out (Escape)', category: 'jjb', muscle: 'ESCAPES', unit: 'reps' },
  { name: 'Running Man Escape', category: 'jjb', muscle: 'ESCAPES', unit: 'reps' },
  { name: 'Buggy Choke', category: 'jjb', muscle: 'SOUMISSIONS', unit: 'reps' },
  { name: 'Suloev Stretch', category: 'jjb', muscle: 'SOUMISSIONS', unit: 'reps' },
  { name: 'Ninja Choke', category: 'jjb', muscle: 'SOUMISSIONS', unit: 'reps' },
  { name: 'Marcelotine', category: 'jjb', muscle: 'SOUMISSIONS', unit: 'reps' },
  { name: 'Mounted Triangle', category: 'jjb', muscle: 'SOUMISSIONS', unit: 'reps' },
  { name: 'Inverted Triangle', category: 'jjb', muscle: 'SOUMISSIONS', unit: 'reps' },
  { name: 'Reverse Triangle', category: 'jjb', muscle: 'SOUMISSIONS', unit: 'reps' },
  { name: 'Arm In Guillotine', category: 'jjb', muscle: 'SOUMISSIONS', unit: 'reps' },
  { name: 'Ten Finger Guillotine', category: 'jjb', muscle: 'SOUMISSIONS', unit: 'reps' },
  { name: 'Power Guillotine', category: 'jjb', muscle: 'SOUMISSIONS', unit: 'reps' },
  { name: 'Short Choke (RNC)', category: 'jjb', muscle: 'SOUMISSIONS', unit: 'reps' },
  { name: 'Mata Leão', category: 'jjb', muscle: 'SOUMISSIONS', unit: 'reps' },

  // ═══════════════════════════════════════════════════════════════
  // EXERCICES SUPPLÉMENTAIRES - BOXE/STRIKING
  // ═══════════════════════════════════════════════════════════════
  { name: 'Double Jab', category: 'boxe', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Jab to the Body', category: 'boxe', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Lead Hook', category: 'boxe', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Rear Hook', category: 'boxe', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Lead Uppercut', category: 'boxe', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Rear Uppercut', category: 'boxe', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Shovel Hook', category: 'boxe', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Liver Shot', category: 'boxe', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Pivot Punch', category: 'boxe', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Check Hook', category: 'boxe', muscle: 'TACTIQUE', unit: 'reps' },
  { name: 'Pull Counter', category: 'boxe', muscle: 'TACTIQUE', unit: 'reps' },
  { name: 'Slip Counter', category: 'boxe', muscle: 'TACTIQUE', unit: 'reps' },
  { name: 'Parry Counter', category: 'boxe', muscle: 'TACTIQUE', unit: 'reps' },
  { name: 'Catch and Shoot', category: 'boxe', muscle: 'TACTIQUE', unit: 'reps' },
  { name: 'Peek-a-Boo Defense', category: 'boxe', muscle: 'DÉFENSE', unit: 'time' },
  { name: 'Philly Shell', category: 'boxe', muscle: 'DÉFENSE', unit: 'time' },
  { name: 'High Guard', category: 'boxe', muscle: 'DÉFENSE', unit: 'time' },
  { name: 'Head Movement Drills', category: 'boxe', muscle: 'DÉFENSE', unit: 'time' },
  { name: 'Slip Bag', category: 'boxe', muscle: 'DÉFENSE', unit: 'time' },
  { name: 'Bob and Weave', category: 'boxe', muscle: 'DÉFENSE', unit: 'reps' },
  { name: 'Roll Under', category: 'boxe', muscle: 'DÉFENSE', unit: 'reps' },
  { name: 'Pull Back', category: 'boxe', muscle: 'DÉFENSE', unit: 'reps' },
  { name: 'L-Step', category: 'boxe', muscle: 'DÉPLACEMENT', unit: 'reps' },
  { name: 'Pivot', category: 'boxe', muscle: 'DÉPLACEMENT', unit: 'reps' },
  { name: 'Step Drag', category: 'boxe', muscle: 'DÉPLACEMENT', unit: 'reps' },
  { name: 'In and Out', category: 'boxe', muscle: 'DÉPLACEMENT', unit: 'time' },
  { name: 'Lateral Movement', category: 'boxe', muscle: 'DÉPLACEMENT', unit: 'time' },
  { name: 'Ring Generalship', category: 'boxe', muscle: 'TACTIQUE', unit: 'time' },
  { name: 'Cutting Off Ring', category: 'boxe', muscle: 'TACTIQUE', unit: 'time' },
  { name: 'Fighting Off Ropes', category: 'boxe', muscle: 'TACTIQUE', unit: 'time' },

  // ═══════════════════════════════════════════════════════════════
  // EXERCICES SUPPLÉMENTAIRES - MUAY THAI/MMA
  // ═══════════════════════════════════════════════════════════════
  { name: 'Lead Teep', category: 'muay_thai', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Rear Teep', category: 'muay_thai', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Side Teep', category: 'muay_thai', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Skip Knee', category: 'muay_thai', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Flying Knee', category: 'muay_thai', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Straight Knee', category: 'muay_thai', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Curve Knee', category: 'muay_thai', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Spear Elbow', category: 'muay_thai', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Horizontal Elbow', category: 'muay_thai', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Uppercut Elbow', category: 'muay_thai', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Downward Elbow', category: 'muay_thai', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Spinning Elbow', category: 'muay_thai', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Clinch Entry', category: 'muay_thai', muscle: 'CLINCH', unit: 'reps' },
  { name: 'Clinch Break', category: 'muay_thai', muscle: 'CLINCH', unit: 'reps' },
  { name: 'Plum Control', category: 'muay_thai', muscle: 'CLINCH', unit: 'time' },
  { name: 'Single Collar Tie', category: 'muay_thai', muscle: 'CLINCH', unit: 'time' },
  { name: 'Double Collar Tie', category: 'muay_thai', muscle: 'CLINCH', unit: 'time' },
  { name: 'Off-Balance (Clinch)', category: 'muay_thai', muscle: 'CLINCH', unit: 'reps' },
  { name: 'Turn (Clinch)', category: 'muay_thai', muscle: 'CLINCH', unit: 'reps' },
  { name: 'Inside Trip', category: 'muay_thai', muscle: 'CLINCH', unit: 'reps' },
  { name: 'Outside Trip', category: 'muay_thai', muscle: 'CLINCH', unit: 'reps' },
  { name: 'Leg Catch Counter', category: 'muay_thai', muscle: 'DÉFENSE', unit: 'reps' },
  { name: 'Check and Return', category: 'muay_thai', muscle: 'DÉFENSE', unit: 'reps' },
  { name: 'Teep Catch', category: 'muay_thai', muscle: 'DÉFENSE', unit: 'reps' },
  { name: 'Parry Kick', category: 'muay_thai', muscle: 'DÉFENSE', unit: 'reps' },
  { name: 'Cage Clinch', category: 'mma', muscle: 'LUTTE', unit: 'time' },
  { name: 'Cage Takedown', category: 'mma', muscle: 'LUTTE', unit: 'reps' },
  { name: 'Cage Trip', category: 'mma', muscle: 'LUTTE', unit: 'reps' },
  { name: 'Dirty Boxing Elbows', category: 'mma', muscle: 'STRIKING', unit: 'reps' },
  { name: 'Fence Escape', category: 'mma', muscle: 'DÉFENSE', unit: 'reps' },
  { name: 'Wall Walk', category: 'mma', muscle: 'DÉFENSE', unit: 'reps' },
  { name: 'Underhook Battle', category: 'mma', muscle: 'LUTTE', unit: 'time' },
  { name: 'Double Underhooks', category: 'mma', muscle: 'LUTTE', unit: 'time' },

  // ═══════════════════════════════════════════════════════════════
  // EXERCICES SUPPLÉMENTAIRES - RUNNING/CARDIO
  // ═══════════════════════════════════════════════════════════════
  { name: '100m Sprint', category: 'running', muscle: 'SPRINT', unit: 'reps' },
  { name: '200m Sprint', category: 'running', muscle: 'SPRINT', unit: 'reps' },
  { name: '400m Sprint', category: 'running', muscle: 'SPRINT', unit: 'reps' },
  { name: '800m Repeat', category: 'running', muscle: 'INTERVALLES', unit: 'reps' },
  { name: '1000m Repeat', category: 'running', muscle: 'INTERVALLES', unit: 'reps' },
  { name: '1600m Repeat', category: 'running', muscle: 'INTERVALLES', unit: 'reps' },
  { name: '30/30 Intervals', category: 'running', muscle: 'INTERVALLES', unit: 'time' },
  { name: '60/60 Intervals', category: 'running', muscle: 'INTERVALLES', unit: 'time' },
  { name: '3min/1min Intervals', category: 'running', muscle: 'INTERVALLES', unit: 'time' },
  { name: 'Pyramid Intervals', category: 'running', muscle: 'INTERVALLES', unit: 'time' },
  { name: 'Kenyan Hills', category: 'running', muscle: 'CÔTES', unit: 'reps' },
  { name: 'Hill Sprints', category: 'running', muscle: 'CÔTES', unit: 'reps' },
  { name: 'Long Hill Climb', category: 'running', muscle: 'CÔTES', unit: 'time' },
  { name: 'Downhill Running', category: 'running', muscle: 'TECHNIQUE', unit: 'km' },
  { name: 'Strides', category: 'running', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Running Drills (A-Skip)', category: 'running', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Running Drills (B-Skip)', category: 'running', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Running Drills (High Knees)', category: 'running', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Running Drills (Butt Kicks)', category: 'running', muscle: 'TECHNIQUE', unit: 'reps' },
  { name: 'Cadence Work (180 BPM)', category: 'running', muscle: 'TECHNIQUE', unit: 'time' },
  { name: 'Race Simulation', category: 'running', muscle: 'COMPÉTITION', unit: 'km' },
  { name: 'Brick Run (Triathlon)', category: 'running', muscle: 'SPÉCIFIQUE', unit: 'km' },
  { name: 'Treadmill Intervals', category: 'running', muscle: 'TAPIS', unit: 'time' },
  { name: '12-3-30 (Incline Walk)', category: 'running', muscle: 'TAPIS', unit: 'time' },

  // ═══════════════════════════════════════════════════════════════
  // EXERCICES SUPPLÉMENTAIRES - CROSSFIT/FONCTIONNEL
  // ═══════════════════════════════════════════════════════════════
  { name: 'Squat Clean', category: 'crossfit', muscle: 'HALTÉRO', unit: 'reps' },
  { name: 'Squat Snatch', category: 'crossfit', muscle: 'HALTÉRO', unit: 'reps' },
  { name: 'Hang Squat Clean', category: 'crossfit', muscle: 'HALTÉRO', unit: 'reps' },
  { name: 'Hang Squat Snatch', category: 'crossfit', muscle: 'HALTÉRO', unit: 'reps' },
  { name: 'Clean Pull', category: 'crossfit', muscle: 'HALTÉRO', unit: 'reps' },
  { name: 'Snatch Pull', category: 'crossfit', muscle: 'HALTÉRO', unit: 'reps' },
  { name: 'Clean High Pull', category: 'crossfit', muscle: 'HALTÉRO', unit: 'reps' },
  { name: 'Snatch High Pull', category: 'crossfit', muscle: 'HALTÉRO', unit: 'reps' },
  { name: 'Snatch Balance', category: 'crossfit', muscle: 'HALTÉRO', unit: 'reps' },
  { name: 'Snatch Grip Push Press', category: 'crossfit', muscle: 'HALTÉRO', unit: 'reps' },
  { name: 'Barbell Muscle Clean', category: 'crossfit', muscle: 'HALTÉRO', unit: 'reps' },
  { name: 'Barbell Muscle Snatch', category: 'crossfit', muscle: 'HALTÉRO', unit: 'reps' },
  { name: 'Front Rack Lunge', category: 'crossfit', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Overhead Walking Lunge', category: 'crossfit', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Barbell Step-ups', category: 'crossfit', muscle: 'JAMBES', unit: 'reps' },
  { name: 'Cluster (Clean + Thruster)', category: 'crossfit', muscle: 'COMPLEXE', unit: 'reps' },
  { name: 'Bear Complex', category: 'crossfit', muscle: 'COMPLEXE', unit: 'reps' },
  { name: 'DT Complex', category: 'crossfit', muscle: 'COMPLEXE', unit: 'reps' },
  { name: 'Linda (3 Bars of Death)', category: 'crossfit', muscle: 'BENCHMARK', unit: 'time' },
  { name: 'Grace (30 C&J)', category: 'crossfit', muscle: 'BENCHMARK', unit: 'time' },
  { name: 'Isabel (30 Snatch)', category: 'crossfit', muscle: 'BENCHMARK', unit: 'time' },
  { name: 'Fran (21-15-9)', category: 'crossfit', muscle: 'BENCHMARK', unit: 'time' },
  { name: 'Diane (21-15-9)', category: 'crossfit', muscle: 'BENCHMARK', unit: 'time' },
  { name: 'Helen (3 rounds)', category: 'crossfit', muscle: 'BENCHMARK', unit: 'time' },
  { name: 'Karen (150 Wall Balls)', category: 'crossfit', muscle: 'BENCHMARK', unit: 'time' },
  { name: 'Jackie', category: 'crossfit', muscle: 'BENCHMARK', unit: 'time' },
  { name: 'Nancy', category: 'crossfit', muscle: 'BENCHMARK', unit: 'time' },
  { name: 'Cindy (20 min AMRAP)', category: 'crossfit', muscle: 'BENCHMARK', unit: 'reps' },
  { name: 'Mary (20 min AMRAP)', category: 'crossfit', muscle: 'BENCHMARK', unit: 'reps' },
  { name: 'Annie (Double Unders + Situps)', category: 'crossfit', muscle: 'BENCHMARK', unit: 'time' },
  { name: 'Strict Muscle Up', category: 'crossfit', muscle: 'GYMNASTIQUE', unit: 'reps' },
  { name: 'L Pull-up', category: 'crossfit', muscle: 'GYMNASTIQUE', unit: 'reps' },
  { name: 'Strict Toes to Bar', category: 'crossfit', muscle: 'GYMNASTIQUE', unit: 'reps' },
  { name: 'Kipping Toes to Bar', category: 'crossfit', muscle: 'GYMNASTIQUE', unit: 'reps' },
  { name: 'Deficit HSPU', category: 'crossfit', muscle: 'GYMNASTIQUE', unit: 'reps' },
  { name: 'Legless Rope Climb', category: 'crossfit', muscle: 'GYMNASTIQUE', unit: 'reps' },
  { name: 'Pegboard', category: 'crossfit', muscle: 'GYMNASTIQUE', unit: 'reps' },
  { name: 'Strict Ring Dip', category: 'crossfit', muscle: 'GYMNASTIQUE', unit: 'reps' },

  // ═══════════════════════════════════════════════════════════════
  // EXERCICES SUPPLÉMENTAIRES - SPORTS DIVERS
  // ═══════════════════════════════════════════════════════════════
  { name: 'Long Swim', category: 'natation', muscle: 'ENDURANCE', unit: 'km' },
  { name: 'Sprint Swim', category: 'natation', muscle: 'VITESSE', unit: 'meters' },
  { name: 'Kick Set', category: 'natation', muscle: 'JAMBES', unit: 'meters' },
  { name: 'Pull Set', category: 'natation', muscle: 'BRAS', unit: 'meters' },
  { name: 'IM Set', category: 'natation', muscle: 'COMPLET', unit: 'meters' },
  { name: 'Descending Set', category: 'natation', muscle: 'INTENSITÉ', unit: 'meters' },
  { name: 'Threshold Set', category: 'natation', muscle: 'SEUIL', unit: 'meters' },
  { name: 'Recovery Swim', category: 'natation', muscle: 'RÉCUP', unit: 'meters' },
  { name: 'Sortie Vallonnée', category: 'velo', muscle: 'MIXTE', unit: 'km' },
  { name: 'Sprint Interval (Vélo)', category: 'velo', muscle: 'PUISSANCE', unit: 'reps' },
  { name: 'Hill Climb Repeat', category: 'velo', muscle: 'FORCE', unit: 'reps' },
  { name: 'Time Trial', category: 'velo', muscle: 'EFFORT', unit: 'km' },
  { name: 'Endurance Ride', category: 'velo', muscle: 'ENDURANCE', unit: 'km' },
  { name: 'Recovery Ride', category: 'velo', muscle: 'RÉCUP', unit: 'km' },
  { name: 'Threshold Intervals', category: 'velo', muscle: 'SEUIL', unit: 'time' },
  { name: 'Criterium Practice', category: 'velo', muscle: 'COMPÉTITION', unit: 'time' },
  { name: 'Yoga Flow', category: 'yoga', muscle: 'FLOW', unit: 'time' },
  { name: 'Warrior Sequence', category: 'yoga', muscle: 'FORCE', unit: 'time' },
  { name: 'Hip Opening', category: 'yoga', muscle: 'MOBILITÉ', unit: 'time' },
  { name: 'Backbend Practice', category: 'yoga', muscle: 'FLEXIBILITÉ', unit: 'time' },
  { name: 'Inversion Practice', category: 'yoga', muscle: 'ÉQUILIBRE', unit: 'time' },
  { name: 'Arm Balance', category: 'yoga', muscle: 'FORCE', unit: 'time' },
  { name: 'Seated Forward Fold', category: 'yoga', muscle: 'ÉTIREMENT', unit: 'time' },
  { name: 'Spinal Twist', category: 'yoga', muscle: 'MOBILITÉ', unit: 'time' },
  { name: 'Core Pilates', category: 'pilates', muscle: 'CORE', unit: 'time' },
  { name: 'Teaser', category: 'pilates', muscle: 'ABDOS', unit: 'reps' },
  { name: 'Swimming (Pilates)', category: 'pilates', muscle: 'DOS', unit: 'reps' },
  { name: 'Single Leg Stretch', category: 'pilates', muscle: 'ABDOS', unit: 'reps' },
  { name: 'Double Leg Stretch', category: 'pilates', muscle: 'ABDOS', unit: 'reps' },
  { name: 'Criss Cross', category: 'pilates', muscle: 'OBLIQUES', unit: 'reps' },
  { name: 'Saw', category: 'pilates', muscle: 'MOBILITÉ', unit: 'reps' },
  { name: 'Spine Stretch', category: 'pilates', muscle: 'FLEXIBILITÉ', unit: 'reps' },
];

// Fonction utilitaire pour compter les exercices
export const getExerciseCount = () => EXERCISE_LIBRARY.length;
